### ISSUE TITLE
Failed to install lumos indexer

### ISSUE THREAD

**Issue by katat** [nervosnetwork/lumos#1]
Hi there,

I am trying to install the npm package `@ckb-lumos/indexer` with the following command:
```
npm i @ckb-lumos/indexer
```

But I got the following error:
```
$ npm i @ckb-lumos/indexer

> xxhash@0.3.0 install /Users/kata/repos/dev/nervos/test-lumos/node_modules/xxhash
> node-gyp rebuild

  CXX(target) Release/obj.target/hash/src/hash.o
In file included from ../src/hash.cc:1:
In file included from ../../nan/nan.h:55:
In file included from /Users/kata/Library/Caches/node-gyp/12.16.2/include/node/uv.h:66:
In file included from /Users/kata/Library/Caches/node-gyp/12.16.2/include/node/uv/unix.h:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:78:10: fatal error:
      'net/net_kev.h' file not found
#include <net/net_kev.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/hash/src/hash.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kata/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/kata/.nvm/versions/node/v12.16.2/bin/node" "/Users/kata/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kata/repos/dev/nervos/test-lumos/node_modules/xxhash
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN test-lumos@1.0.0 No description
npm WARN test-lumos@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxhash@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxhash@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kata/.npm/_logs/2020-05-22T23_49_05_390Z-debug.log
```

My development environment:
 - macOS 10.15.4
 - nodejs v12.16.2
 - xcodebuild 11.4.1

Do you know the possible causes of this error?

Thanks

**Comment by xxuejie** [comment]
I think the problem is happening when your system tries to compile a native node module. So I would suggest double check xcode related part, for example see if xcode command line tool is installed etc.

**Comment by xxuejie** [comment]
BTW I just tried the above steps on my mac machine and it works okay. The only thing I forgot, is that the latest npm published version is still 0.1.3, which does not have pre-built binary so Rust is needed on your system. I've just published 0.1.6 which should be able to leverage pre-built binaries. But that is really a separate problem from this issue. This issue is more about making sure the C++ compiler required by node on your laptop works all good.

**Comment by katat** [comment]
Thanks @xxuejie for the updates.

I have also tried to install on my older mac which runs macOS 10.14, and the installation works fine.

So it is probably an issue on my current development environment, which runs on MacOS 10.15.4. I am sure both the latest version of Xcode and C++ compiler is installed. 

Just try to isolate the potential causes, could you please tell me which MacOS version you are using when running the installation?

**Comment by xxuejie** [comment]
I use a Mojave based test environment, which I assume it is 10.14.

And to reproduce the issue, you don't really need lumos indexer, all you really need is any npm package that has a C compiling part, for example `npm i xxhash`.

**Comment by katat** [comment]
I think I figured out the cause. It is related to the Xcode's active developer directory. 

Somehow my development environment uses the `/Applications/Xcode.app/Contents/Developer/` as the base file path for doing the C related compilation. However, the base file path is should be based on the Xcode command-line tool's sub folder `/Library/Developer/CommandLineTools`.

After running the command line to switch the active developer directory, the installation works good.
```
xcode-select -s /Library/Developer/CommandLineTools
```

Thanks a lot for the help.
