### ISSUE TITLE
Query with argsLen

### ISSUE THREAD

**Issue by katat** [nervosnetwork/lumos#101]
I am trying to query cells using the `argsLen` filter with the following script:

```js
const lockScript = {
    code_hash: '0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8',
    hash_type: 'type',
    args: '0x405ee3f9b00b2df390ff04669967c70c90914c2b'
};

const cellCollector = new CellCollector(indexer, {
    lock: lockScript,
    argsLen: 20
});

const cells = [];
for await (const cell of cellCollector.collect()) 
    cells.push(cell);
```

But it is not able to locate the cells that are already on-chain. https://explorer.nervos.org/aggron/transaction/0x6b6a67af7b9401b937e6985e30c0b74afbf1bd3bf758161be6b9f7584678261c#0

Is it due to incorrect query parameters, or something else?

**Comment by classicalliu** [comment]
`argsLen` should be `28` here

https://github.com/nervosnetwork/lumos/blob/develop/packages/base/index.d.ts#L95

**Comment by katat** [comment]
Now I got it work. Thanks @classicalliu
