### ISSUE TITLE
M1 processor installation problem

### ISSUE THREAD

**Issue by happylolonly** [nervosnetwork/lumos#161]
I have M1 processor and have an error during installation.
How should I fix it?
 
![image](https://user-images.githubusercontent.com/18665326/128470813-c40b77f4-6ea1-4485-83a2-5a264df88ff4.png)

**Comment by happylolonly** [comment]
I temporary fixed it with https://stackoverflow.com/questions/65342769/install-node-on-m1-mac

**Comment by e00dan** [comment]
I prepared PR that should fix this: https://github.com/nervosnetwork/lumos/pull/164

**Comment by flyer88** [comment]
I have the same question

**Comment by homura** [comment]
lumos >= 0.17 has supports the M1 chip, but indexer may need to do migration, to migrate to lumos@0.17 we can check this [doc](https://github.com/nervosnetwork/lumos/blob/develop/packages/ckb-indexer/mirgation.md)
