### ISSUE TITLE
Some clarity on error thrown 

### ISSUE THREAD

**Issue by Leon-Africa** [nervosnetwork/lumos#162]
Hi there,

I am currently reading through the code - could you please elaborate on what the following error means?

https://github.com/nervosnetwork/lumos/blob/develop/packages/common-scripts/src/common.ts
````
if (deductAmount > 0n) {
    throw new Error("Not enough capacity in from infos!");
  }
````

**Comment by classicalliu** [comment]
It means capacity in from infos not enough for injectCapacity / transfer or payFee.

**Comment by Leon-Africa** [comment]
Sure but what are these in the context of Nervos Network.

Where are the definitions/documentation for:
"capacity"
"infos" 
"from" (I'm supposing it is referring only to the account from which the transaction is coming)
"injectCapacity "

**Comment by homura** [comment]
Close the issue due to inactivity
