### ISSUE TITLE
Supports querying on live cells with type hash

### ISSUE THREAD

**Issue by katat** [nervosnetwork/lumos#19]
At the moment, to transact with a UDT, the users have to enter the `typeScript.args` in the UI and `typeScript.codeHash` is hardcoded to targeting the sUDT. In the future, both the `args` and `codeHash` would be dynamic variables, so we shouldn't hardcode them at that stage. On the other hand, requiring the users to enter both the variables are cumbersome and error-prone. Ideally, the users should only need to enter a unique identifier to locate the UDT they want to operate on.

Therefore, in the use case of UDT in Neuron, we need to be able to locate a type script with a type hash, which is the identifier used on the [Explorer sUDT page](https://explorer.nervos.org/aggron/sudt/0x1c5f32c5efb08ac256bd9413c30eef7420ae54f30ff11075967b89570326c295). Being able to locate the cells using a type hash is not only more friendly to the users, but also its user experience is more consistent with the identifier used in the Explorer.

Thus, I am wondering if it is possible to have lumos indexer supports querying on type hash since it will be very useful for both Neuron and the 3rd party clients.

As this may involve the change to the `ckb-indexer`, I guess @quake may help in providing some guidelines here as well.

**Comment by xxuejie** [comment]
lumos, and the underlying `ckb-indexer`, actually do support querying only on `code hash` + `hash type`, but not `args`. In fact, what ckb-indexer does is that it does `prefix search`: it would serialize `code hash`, `hash type` and `args` into a flat array, and use it as a prefix to locate all related cells. That means if you use empty args, you are basically searching all cells with matching `code hash` and `hash type`.

**Comment by xxuejie** [comment]
Apart from that, I do want to want to learn what you mean when you say "locate a type script with a type hash", what is `type hash` here specifically?

**Comment by katat** [comment]
> Apart from that, I do want to want to learn what you mean when you say "locate a type script with a type hash", what is type hash here specifically?

Sorry for the confusion here. I mean the hash of a type script.

**Comment by xxuejie** [comment]
I'm really not sure what the hash of the type script alone can do. All you can do is querying some cells, there won't be any further action that can be performed on a hash of type script alone. Part of me even hold the feeling it is a mistake for us to introduce the concept of hash of type script, we should always just use the script.

If the ultimate goal here is to allow representing a UDT with a single identifier, why not just concat `code_hash`, `hash_type` and `args` of a type script? If that feels too long, I think we should introduce some naming solution much like what we have as CKB address.

**Comment by katat** [comment]
Thanks for the suggestion. 
We think having type script address to do this makes a lot of sense.
