### ISSUE TITLE
Fail to compile when using indexer

### ISSUE THREAD

**Issue by zhangyouxin** [nervosnetwork/lumos#194]
env:
os: macos big sur 11.2.3
node: 14.15.0
version: @ckb-lumos/indexer@^0.18.0-rc1

my project was created via create-react-app, when I ran following code:

```javascript
const { Indexer } = require("@CKB-lumos/indexer");
const indexer = new Indexer("http://127.0.0.1:9114", "/tmp/indexed-data");
indexer.startForever();
```

and this produces following error:

![snapshot](https://cdn.discordapp.com/attachments/852410844192702485/910809934562750474/unknown.png)

**Comment by homura** [comment]
the `@ckb-lumos/indexer` only works with NodeJS, to work with a browser we need to use `@ckb-lumos/ckb-indexer`
