### ISSUE TITLE
Can't use Buffer in browser environment

### ISSUE THREAD

**Issue by zhangyouxin** [nervosnetwork/lumos#199]
`Buffer` can be used in Node environment but can't be recognized in browser

![image](https://user-images.githubusercontent.com/3870972/143354097-173405f5-ca11-4d7f-b525-7b42182e3694.png)

**Comment by homura** [comment]
lumos@0.17.0-rc6 has provided a new browser bundle @ckb-lumos/lumos, using the bumdle could avoid the error
