### ISSUE TITLE
Migrate helpers and common-scripts into TypeScript

### ISSUE THREAD

**Issue by xxuejie** [nervosnetwork/lumos#23]
Right now lumos is written in pure JavaScript, but as logics are getting more and more complicated, the maintenance burden also arises. We might want to move the 2 slightly complicated packages, helpers and common-scripts into TypeScript to leverage internal type checking.

Notice the fundamental design principle of lumos is not changed: it is designed for both TypeScript and JavaScript usage, and no security should be affected when a developer chooses JavaScript over TypeScript. What we are talking here, is simply the reliance of TypeScript for internal type logic checking.

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/lumos/pull/47
https://github.com/nervosnetwork/lumos/pull/60
