### ISSUE TITLE
Transaction collector bugfix

### ISSUE THREAD

**Issue by jpeersyst** [nervosnetwork/lumos#278]
Hello! I am currently using lumos to develop a nervos wallet and I found a bug in the transaction collector of ckb-indexer package which I think I could fix correctly. I will be explaining here when it happens and what I did to fix it.

I also created a PR fixing this issue: [Transaction collector input fix](https://github.com/nervosnetwork/lumos/pull/280)

I stumbled upon this bug using transaction collector to fetch the transactions of my test address [ckt1qyqdlj9dyxgh3gc8lughae8zlemqe5vyzznsnmhy7w](https://explorer.nervos.org/aggron/address/ckt1qyqdlj9dyxgh3gc8lughae8zlemqe5vyzznsnmhy7w) more precisely because of the transaction [0x87c3586cc91ec7a1a97407456dba0adb34c5781c6031cb71bfb175939af4e6c6](https://explorer.nervos.org/aggron/transaction/0x87c3586cc91ec7a1a97407456dba0adb34c5781c6031cb71bfb175939af4e6c6).

The file in which the error was thrown is [transaction_collector.ts](https://github.com/nervosnetwork/lumos/blob/develop/packages/ckb-indexer/src/transaction_collector.ts#L21).
An error would throw saying can not read lock of undefined. As I will explain I think I found the root of the bug. It originated in this part of the code:
```
121    if (txIoTypeInputOutPointList.length > 0) {
122      await services
123        .requestBatch(this.CKBRpcUrl, txIoTypeInputOutPointList)
124        .then((response: GetTransactionRPCResult[]) => {
125          response.forEach((item: GetTransactionRPCResult) => {
126            const itemId = item.id.toString();
127            const [cellIndex, transactionHash] = itemId.split("-");
128            const output: Output =
129              item.result.transaction.outputs[parseInt(cellIndex)];
130            const targetTx = transactionList.find(
131              (tx) => tx.transaction.hash === transactionHash
132            );
133            if (targetTx) {
134              targetTx.inputCell = output;
135            }
136          });
137        });
138    }
139
140    //filter by ScriptWrapper.argsLen
141    transactionList = transactionList.filter(
142      (transactionWrapper: TransactionWithIOType) => {
143        if (
144          transactionWrapper.ioType === "input" &&
145          transactionWrapper.inputCell
146        ) {
147          return this.isCellScriptArgsValid(transactionWrapper.inputCell);
148        } else {
149          const targetCell: Output =
150            transactionWrapper.transaction.outputs[
151              parseInt(transactionWrapper.ioIndex)
152            ];
153          return this.isCellScriptArgsValid(targetCell);
154        }
155      }
156    );
```

The problem was that line 153 would call the function isCellScriptArgsValid with targetCell undefined. After that when the function tried to get the property lock of that targetCell it would fail. This is due to two thing mainly. The first one is that the transactionList contained more than 1 transaction of type input same transaction hash and different inputIndex. As a result in line 130 only finds the first transaction with that hash in the list and does not populate the field inputCell of all possible combinations. Later on on the code because of the if in the line 143 as it had no inputCell even though was of input type it would go to the else and try to get the `transactionWrapper.transaction.outputs[2]` as the transaction was looking for the input with index 2 and it looked in the outputs of index 2 when there are only 2 outputs instead of 3 as you can see in the transaction I linked earlier ( [0x87c3586cc91ec7a1a97407456dba0adb34c5781c6031cb71bfb175939af4e6c6](https://explorer.nervos.org/aggron/transaction/0x87c3586cc91ec7a1a97407456dba0adb34c5781c6031cb71bfb175939af4e6c6)),

The solution is short and easy to implement:
```
105    //get input cell transaction batch
106    const txIoTypeInputOutPointList: any[] = [];
107    transactionList.forEach((transactionWrapper) => {
108      if (transactionWrapper.ioType === "input") {
109        const targetOutPoint: OutPoint =
110          transactionWrapper.transaction.inputs[
111            parseInt(transactionWrapper.ioIndex)
112          ].previous_output;
113        const id =
114          targetOutPoint.index + "-" + transactionWrapper.transaction.hash;
115        if (!txIoTypeInputOutPointList.some((txReq) => txReq.id === id)) {
116          txIoTypeInputOutPointList.push({
117            id,
118            jsonrpc: "2.0",
119            method: "get_transaction",
120            params: [targetOutPoint.tx_hash],
121          });
122        }
123      }
124    });
125    if (txIoTypeInputOutPointList.length > 0) {
126      await services
127        .requestBatch(this.CKBRpcUrl, txIoTypeInputOutPointList)
128        .then((response: GetTransactionRPCResult[]) => {
129          response.forEach((item: GetTransactionRPCResult) => {
130            const itemId = item.id.toString();
131            const [cellIndex, transactionHash] = itemId.split("-");
132            const output: Output =
133              item.result.transaction.outputs[parseInt(cellIndex)];
134            const targetTxs = transactionList.filter(
135              (tx) =>
136                tx.transaction.hash === transactionHash &&
137                tx.ioType === "input" &&
138                tx.transaction.inputs[parseInt(tx.ioIndex)].previous_output
139                  .index === cellIndex
140            );
141            targetTxs.forEach((targetTx) => (targetTx.inputCell = output));
142          });
143        });
144    }
```
Firstly I implemented a check to not put same transaction twice in line 115. Later, as you can see in line 134, we filter for all the transactions with the same hash of ioType input (to not set inputCell on output transactions as we do not need it) and with the same transaction previous output index and then we set their inputCell.

I'd like if it could be implemented and pushed as it would improve the code in some instances.

**Comment by homura** [comment]
Thank you for your issue, as you said, the problem is in the `TransactionCollector`, when more than one `OutPoint` needs to be resolved to a `Cell`, the collector does not work as expected and causes an error. We will add the relevant test case and release a new version as soon as possible.

**Comment by homura** [comment]
this PR fixed the bug https://github.com/nervosnetwork/lumos/pull/282

**Comment by jpeersyst** [comment]
I am closing the issue as it has been solved. Thanks for the fast replies!!
