### ISSUE TITLE
Using common-scripts to deposit in DAO

### ISSUE THREAD

**Issue by jpeersyst** [nervosnetwork/lumos#279]
Hello! I am currently developing a nervos wallet and I found what I think is an issue related to the creation in transactions.
I found this issue trying to deposit in DAO from the address [ckt1qyqdlj9dyxgh3gc8lughae8zlemqe5vyzznsnmhy7w](https://explorer.nervos.org/aggron/address/ckt1qyqdlj9dyxgh3gc8lughae8zlemqe5vyzznsnmhy7w) which owns some tokens and already has money deposited in the DAO.

The first thing i wanted to ask is if this should be the correct way of doing. What I mean is if it is correct to use the same address to store the CKB and the assets as if I had used another one this would no happen. In the case I should do differently I would like to know how but in cas all of this should work anyway I will explain the issue below:

When using `common-scripts` deposit function the injected capacity looks like this:
```
"inputs": [
    {
      "cell_output": {
        "capacity": "0x174876e800",
        "lock": { ... },
        "type": {
          "args": "0x",
          "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
          "hash_type": "type"
        }
      },
      "data": "0x785a440000000000",
      "out_point": {
        "index": "0x0",
        "tx_hash": "0x805168dafc0c10ae31de2580541db0f5ee8ff53afb55e39a5e2eeb60f878553f"
      },
      "block_number": "0x44a5f1"
    },
    {
      "cell_output": {
        "capacity": "0x746a528800",
        "lock": { ... },
        "type": {
          "args": "0x",
          "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
          "hash_type": "type"
        }
      },
      "data": "0x0000000000000000",
      "out_point": {
        "index": "0x0",
        "tx_hash": "0x6d22619e2866924f585b440543927bb4d21b8bdfac6e415fa156fc66f6a97af0"
      },
      "block_number": "0x44d525"
    },
    {
      "cell_output": {
        "capacity": "0xba43b7400",
        "lock": { ... },
        "type": {
          "args": "0x",
          "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
          "hash_type": "type"
        }
      },
      "data": "0x0000000000000000",
      "out_point": {
        "index": "0x0",
        "tx_hash": "0x87c3586cc91ec7a1a97407456dba0adb34c5781c6031cb71bfb175939af4e6c6"
      },
      "block_number": "0x44f48a"
    },
    {
      "cell_output": {
        "capacity": "0xe8d4a51000",
        "lock": { ... },
        "type": null
      },
      "data": "0x",
      "out_point": {
        "index": "0x0",
        "tx_hash": "0x62e2b992ca219b27e7c508e65c0bacd92403a467a213cbc1d148d09cd8a553ae"
      },
      "block_number": "0x44f639"
    }
  ]
```
As you can see the first three inputs injected have a type and are actually of the type of DAO. This means these are cells that have either deposited or withdraw ckbs and, of course, can not be used to deposit in the DAO.
In my case, as the type of lock is `secp256k1_blake160` it uses its `injectCapacity` function to inject it. There the `transferCompatible` function collects the cells to set the input.
I've seen that changing this part of the code ([secp256k1_blake160.ts](https://github.com/nervosnetwork/lumos/blob/develop/packages/common-scripts/src/secp256k1_blake160.ts#L422)):
```
422    const cellCollector = cellProvider.collector({
423      lock: fromScript,
424    });
```
to:
```
422    const cellCollector = cellProvider.collector({
423      lock: fromScript,
424      type: "empty",
425    });
```
makes it work correctly. What I am not sure is if this would break other part of the code. Maybe this could be parametrized depending who calls it?
Having type "empty" ensures the capacity is from free cells and not from other like dao, sudt or nft types which may o may not be correct.
Is it possible am I doing something wrong and I could achive this in another way?

Thanks in advance for your time!!

**Comment by homura** [comment]
Hi @jpeersyst, CellProvider is actually just an interface. In transfer scenarios, CellProvider only focuses on the `fromAddress`, and it is actually up to the `CellProvider` implementation to decide how to collect cells. 

However, in general, lumos also provides common CellProviders, for example, secp256k1 provider is actually an empty type provider [empty type provider](https://github.com/nervosnetwork/lumos/blob/3bd45fa8dcbdbb67e317778298338c867bf7b34d/packages/common-scripts/src/secp256k1_blake160.ts#L61) by default

But when we really need the CellProvider to provide only certain cells that lumos does not provide, we can implement the CellProvider

```ts
import { CellProvider, CellCollector } from '@ckb-lumos/base';

class MyCellProvider implements CellProvider {
  collector(queryOptions: QueryOptions): CellCollector {
    return new MyCellCollector({ ...queryOptions, ...myAdditionalQueryOptions })
  }
} 
```

**Comment by jpeersyst** [comment]
Thanks for the explanation! I am closing the issue
