### ISSUE TITLE
[feat] ScriptConfig includes ARGS field

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/lumos#344]
I would like to manage scripts with `ScriptConfig`. As some of my scripts are not args-empty, I have to handle them specifically. Why does `ScriptConfig` exclude `ARGS` and is it possible to include `ARGS`? `ARGS` is part of a script, I think it is useful for developers that support managing these scripts with non-empty args.

https://github.com/nervosnetwork/lumos/blob/bba6b4db382638250910a3d7224ac1b56527ad0b/packages/config-manager/src/types.ts#L2-L10

**Comment by homura** [comment]
The `ScriptConfig` is designed for managing needed scripts' deployed info in a dApp

- `CODE_HASH` + `HASH_TYPE` for determined which deployed code should be used for a script in a cell
- `TX_HASH` + `INDEX` + `DEP_TYPE` for determined which `OutPoint` should be used for `CellDeps`

These configs are usually static constants, whereas args are generally not constants

```ts
const tx = {
  cellDeps: [
    {
      tx_hash: CONFIG.SECP256K1_BLAKE160.TX_HASH,
      index: CONFIG.SECP256K1_BLAKE160.INDEX,
      dep_type: CONFIG.SECP256K1_BLAKE160.DEP_TYPE
    }
  ],
  outputs: [
    { 
      code_hash: CONFIG.SECP256K1_BLAKE160.HASH_TYPE, 
      hash_type: CONFIG.SECP256K1_BLAKE160.HASH_TYPE,
      args: "0xMY_PUBLIC_KEY_HASH" // args is not a static constant
    }
  ]
  ...
}
```

There may be scenarios where args is a constant, but we don't recommend hard coding it directly in ScriptConfig either, as it's not easy to understand, maybe write it as a named constant in the application and then use it

```ts

// we assume that deposit and withdrawal implemented in a contract
const DEPOSIT_LOCK_ARGS = '0x...'
const WITHDRAW_LOCK_ARGS = '0x...'

const depositTx = {
  outputs: [
    {
      args: CHARGE_LOCK_ARGS
    }
  ],
  ...
}

const withdrawTx = {
  outputs: [
    {
      args: WITHDRAW_LOCK_ARGS
    }
  ]
}

```

**Comment by keroro520** [comment]
> The ScriptConfig is designed for managing needed scripts' deployed info in a dApp
> 
> CODE_HASH + HASH_TYPE for determined which deployed code should be used for a script in a cell
> TX_HASH + INDEX + DEP_TYPE for determined which OutPoint should be used for CellDeps

Thank you for such a detailed reply.
I understand the design principles. But the above design principles sound like it is more like "script code config" than "script config".
A script has ARGS, while script code doesn't.

**Comment by keroro520** [comment]
A common deployment is like:
1. Deploy a cell that `cell.data` is the script code
2. Construct scripts using the above script code, `Script { code_hash: <referenced to the above script code>, args: <self-defined args> }`

The current `ScriptConfig` is for script code only.

**Comment by keroro520** [comment]
Close this issue since I understand the purpose of this module, https://github.com/nervosnetwork/lumos/issues/344#issuecomment-1122103168, it is a good principle.
