### ISSUE TITLE
Documentation for newcomer

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#393]
## Motivation

As a newcomer to CKB, I'd like to get a primer on CKB and Lumos, it would be helpful to have a document that tells me how to use Lumos to interact with CKB

## How

It would be very helpful to have a tutorial, which could be structured like

- Creating a wallet
- Claiming the test CKB from the test network faucet
- Checking the CKB balance
- Sending my first transaction, which could be a simple CKB transfer (in fact, for the UTxO model, the transfer is not as intuitive as for the account model, so it is not quite as simple)
- Creating a token (similar to ERC20)
- Transferring token to Alice
- Checking Alice's token balance

**Comment by PainterPuppets** [comment]
## Creating a wallet
Using service
 - ckit(metamask)
 - doc-tools (private key to address)

Creted by code
 - crete privateKey by ec2 & generate address

## Claiming the test CKB from the test network faucet
https://faucet.nervos.org/

## Checking the CKB balance
[explore](https://pudge.explorer.nervos.org/)

## Sending my first transaction, which could be a simple CKB transfer
 (in fact, for the UTxO model, the transfer is not as intuitive as for the account model, so it is not quite as simple)
 - set coding envrioment
 - Write some code with Lumos
…
 - send transaction
 - Check transaction by [explore](https://pudge.explorer.nervos.org/)

## Creating a token (similar to ERC20)
 - SUDT description & RFC

 - write sudt issue code by lumos
…
 - send transaction
 - Check transaction by [explore](https://pudge.explorer.nervos.org/)

## Transferring token to Alice

## Checking Alice's token balance

**Comment by homura** [comment]
> * ckit(metamask)

the purpose of this doc is for how to use Lumos to interact with CKB, not only for new to CKB

**Comment by PainterPuppets** [comment]
## hello newcomer step by step

### Overview
todo

### install
`ckb-lumos` is written in TypeScript and use `babel` transfer to Javascript. If you're not familiar with `Node.js`, it's a JavaScript runtime built on Chrome's V8 JavaScript engine. It's the most popular solution to run JavaScript outside of a web browser and `Lumos` is built on top of it.

You can get install Node.js help from [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)

Install `ckb-lumos` by npm
`npm install @ckb-lumos/lumos` 
Or use yarn
`yarn add @ckb-lumos/lumos`

### Example: Create a wallet 
this section will learn 'how to create wallet with @ckb-lumos'

对于一个钱包来说，最重要以及最常用的功能是查看自己的账户(address)以及余额，Nervos中并不限定密码学原语，甚至可以用eth的钱包来创建nervos address，但是为了简单，本文档创建一个椭圆曲线加密算法创建一个账户

这里有一份工具可以帮助你生成一个address: https://ckb.tools/generator 或者如果你想详细了解，具体步骤会在下方列出

#### step1: Generate private key
`elliptic` 是一个帮助我们使用椭圆曲线加密算法的库，你可以运行`npm install elliptic` 来下载

``` ts
import { ec } from "elliptic";

const privateKey = new ec("secp256k1").genKeyPair().getPrivate();

console.log(`0x${privateKey.toString("hex")}`);
```

恭喜你，我们现在拥有了一个private key, 如果你运行这段代码可以看到这是一段类似于`0xbdaf10df03d9c4c356fc8378b9e01978d5bd3ac8acf68195d462d7697a5b518a`这样的字符串, 为了更好的标明这段字符串是一个十六进制的，我们手动加上了0x的前缀，

#### step2: generate address by private key

当你拥有一个private key后，你可以使用@ckb-lumos来生成一个ckb地址

ckb拥有一个测试链arggon和一个正式环境链Lina以及你也可以自己去运行一个本机的 dev net, lumos可以帮助用户在不同的链上进行开发，在本示例中将会使用测试环境，使用`config.predefined.AGGRON4`就可以获取一些测试环境上需要的数据

``` ts
import { hd, config, helpers } from '@ckb-lumos/lumos';

const privateKey = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' // your private key

const pubKey = hd.key.privateToPublic(privateKey);
const args = hd.key.publicKeyToBlake160(pubKey);
const template = config.predefined.AGGRON4.SCRIPTS["SECP256K1_BLAKE160"]!;
const lockScript = {
  code_hash: template.CODE_HASH,
  hash_type: template.HASH_TYPE,
  args: args,
};
const address = helpers.encodeToAddress(lockScript, { config: config.predefined.LINA });
console.log(address)
```
或许你会疑问这些东西都是啥，但是先别着急，后文中会慢慢解释，首先运行一下这段代码，你应该能看到一个以ckt为开头的输出,恭喜你, 你已经成功的创建出了一个ckb的地址，后文中我们会使用这个地址做许多事

### Example: Checking the CKB balance

在上文中我们知道了如何使用ckb生成一个地址，本篇中我们会学习如何查询这个地址的余额，以及从哪里能获取到一些测试代币

#### step 1: Config
ckb节点提供了一些rpc方法来支持用户搜索一些链上数据，但是许多链上数据索引起来非常麻烦，为了方便检索，ckb还提供了一个indexer项目，帮助对链上数据进行索引和速查，我们首先配置一下项目中会用到的ckb rpc和indexer的设置

``` ts
import { RPC, Indexer } from '@ckb-lumos/lumos';
const CKB_RPC_URL = "https://testnet.ckb.dev/rpc";
const CKB_INDEXER_URL = "https://testnet.ckb.dev/indexer";

const rpc = new RPC(CKB_RPC_URL);
const indexer = new Indexer(CKB_INDEXER_URL, CKB_RPC_URL);
```

#### step 2: Collect Cell with Indexer
终于到了激动人心的查询环节，在ckb中，我们把存储数据的单元称之为`Cell`, 而ckb余额作为Cell的capacity属性，当我们想知道自己有多少余额的时候就需要找到自己所有的Cell

``` ts
import { BI, helpers } from '@ckb-lumos/lumos';

export async function getBalance(address: string): Promise<BI> {
  const collector = indexer.collector({
    lock: helpers.parseAddress(address),
  });

  let balance = BI.from(0);
  for await (const cell of collector.collect()) {
    balance = balance.add(cell.cellOutput.capacity);
  }

  return balance;
}
```

恭喜，我们现在创建了一个获取余额的函数，现在可以输出一下看看我们刚刚创建的address中有多少ckb
``` ts
console.log(`address: ${address}`)
getBalance(address).then(capacity => console.log(`balance: ${capacity.toString()} CKB`))
```
或许你会获得一个类似这样的输出

```
address: <your-address>
balance: 0 CKB
```

### Step 4: Get test ckb from faucet
看起来我们现在还没有任何CKB，别难过，ckb的测试网提供了一个水龙头，我们可以从水龙头中获取一些ckb，点击[这里](https://faucet.nervos.org/)来访问水龙头

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/22258327/188526028-93e26b00-c79d-4e17-b2d5-1b1c8b8071bb.png">

打开后你或许会看到这样一个页面，现在将我们之前生成的address填入中间的输入框后点击Claim按钮，之后你会看到网页中多了一条这样的数据

<img width="987" alt="image" src="https://user-images.githubusercontent.com/22258327/188526096-fd1e91bb-4f83-4c95-aed1-8b054e350d0d.png">

在等待大约10s左右后，这条数据的状态会从Pending变成Processed，让我们再次运行我们的钱包项目，检查一下我们的余额

``` ts
address: <your-address>
balance: 10000 CKB
```
看起来目前为止咱们的钱包项目运行的没什么问题，咱们现在有CKB了，但是光查看CKB是没用的，还需要让这笔CKB可以自由转账，在下节中将学会一个转账的实例

### Example: Sending my first transaction, which could be a simple CKB transfer 
假设bob是一家披萨店，你用了100个CKB向bob订购了一个披萨，现在需要给bob支付这100个ckb，bob告诉你他的address是：`ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgy5rtexzvhk7jt7gla8wlq5lztf79tjhg9fmd4f`

#### Step1: Config
首先要做的事依然是设置我们的环境，下面这段代码可以让lumos默认使用测试网络的设置，而不是每次都需要显式的设置环境

``` ts
import { config } from '@ckb-lumos/lumos';

config.initializeConfig(config.predefined.AGGRON4);
```

#### Step2: Build transaction
`@ckb-lumos`中提供了一些常用的方法，而转账ckb正是一个最常用的方法，我们可以使用这`common`中的方法来帮助我们构造这笔交易

``` ts
import { helpers, commons } from '@ckb-lumos/lumos';

const transfer = async() => {
    let txSkeleton = helpers.TransactionSkeleton({ cellProvider: indexer });
    txSkeleton = await commons.secp256k1Blake160.transfer(
        txSkeleton,
        '<your-address>',
        'ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgy5rtexzvhk7jt7gla8wlq5lztf79tjhg9fmd4f',
        BigInt(100 * 10 ** 8),
    );
}
```

#### Step3: Pay fee
现在我们已经构造出来一个基础的交易，我们给bob转账100个ckb，但是为了让这笔交易成功被打包上链，我们还需要给矿工支付一些fee，lumos中提供了一些方法来支付fee，在这个实例中为了简单起见，我们将交易费设置为1ckb，在正常交易中手续费会根据交易的大小计算，通常会比1ckb低很多很多。

``` ts

import { helpers, commons } from '@ckb-lumos/lumos';

const transfer = async() => {
    let txSkeleton = helpers.TransactionSkeleton({ cellProvider: indexer });
    txSkeleton = await commons.secp256k1Blake160.transfer(
        txSkeleton,
        '<your-address>',
        'ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgy5rtexzvhk7jt7gla8wlq5lztf79tjhg9fmd4f',
        BigInt(100 * 10 ** 8),
    );

    txSkeleton = await commons.secp256k1Blake160.payFee(
      txSkeleton,
       '<your-address>',
      BigInt(1 * 10 ** 8),
    );
}
```

#### Step4: Signing and sending
现在我们已经构造出来一个交易的数据结构，任何人都可以创造出来这样一个结构，但是要如果谁都能发起这笔交易的话，你钱包里的ckb就会被其他人拿走，所以为了确信交易是cell的拥有者授权发布的，我们还需要为这个交易签名，`@ckb-lumos`提供了一些方法可以帮助我们生成交易的简述以及使用椭圆螺旋曲线算法签名，最后我们使用上文中创建的rpc来将交易发布到区块链上

``` ts
import { BI, hd, config, helpers, RPC, Indexer, commons } from '@ckb-lumos/lumos';
const transfer = async() => {
  let txSkeleton = helpers.TransactionSkeleton({ cellProvider: indexer });
  txSkeleton = await commons.secp256k1Blake160.transfer(
    txSkeleton,
    address,
    to,
    BigInt(100 * 10 ** 8),
  );
  
  txSkeleton = await commons.secp256k1Blake160.payFee(
    txSkeleton,
    address,
    BigInt(1 * 10 ** 8),
  );
  
  txSkeleton = commons.common.prepareSigningEntries(txSkeleton);
  const message = txSkeleton.get("signingEntries").get(0)?.message;
  const Sig = hd.key.signRecoverable(message!, privateKey);
  const tx = helpers.sealTransaction(txSkeleton, [Sig]);

  const txHash = await rpc.sendTransaction(tx, "passthrough");
  console.log(`txHash is: ${txHash}`)
}
```

让我们运行一下这个transfer函数，我们就能看到一个类似`txHash is: 0x998dd1ec986ad0f1aff5f527dc3e9fe13cba0d20ee2e7ee0ce83af213cd399c4`这样的输出，让我们上[区块浏览器](https://pudge.explorer.nervos.org/)中查询一下这笔交易

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/22258327/188527969-0e7b81e0-8c5f-42f8-8278-0b73d81ee7de.png">


我们可以看到交易的内容确实将一个10000ckb的cell消费了，并且为bob生成了一个100ckb的cell以及给自己产生了一笔9899ckb的找零，其中1ckb作为手续费给了矿工，
恭喜！现在你可以躺在沙发上等待享用美味的披萨了

### Advanced: Creating a token (similar to ERC20)
或许你有听说过shiba币，在2021年时非常热门，不知道你有没有过一点好奇，为什么区块链上能出现那么多种不同的代币，在本章节中，我们会发行一个猫猫币，可以送给朋友或者作为积分发放给你的俱乐部成员

``` ts
const issueToken = async () => {
  let txSkeleton = helpers.TransactionSkeleton({ cellProvider: indexer });
  txSkeleton = await commons.sudt.issueToken(
    txSkeleton,
    address,
    1000,
  );

  txSkeleton = await commons.secp256k1Blake160.payFee(
    txSkeleton,
    address,
    BigInt(1 * 10 ** 8),
  );
  
  txSkeleton = commons.common.prepareSigningEntries(txSkeleton);
  const message = txSkeleton.get("signingEntries").get(0)?.message;
  const Sig = hd.key.signRecoverable(message!, privateKey);
  const tx = helpers.sealTransaction(txSkeleton, [Sig]);

  const txHash = await rpc.sendTransaction(tx, "passthrough");
  console.log(`txHash is : ${txHash}`)
}
```

### Advanced: Transferring sudt token to Alice

``` ts
const transferToken = async() => {
  let txSkeleton = helpers.TransactionSkeleton({ cellProvider: indexer });
  txSkeleton = await commons.sudt.transfer(
    txSkeleton,
    [address],
    args,
    to,
    100,
  );

  txSkeleton = await commons.secp256k1Blake160.payFee(
    txSkeleton,
    address,
    BigInt(1 * 10 ** 8),
  );
  
  txSkeleton = commons.common.prepareSigningEntries(txSkeleton);
  const message = txSkeleton.get("signingEntries").get(0)?.message;
  const Sig = hd.key.signRecoverable(message!, privateKey);
  const tx = helpers.sealTransaction(txSkeleton, [Sig]);

  const txHash = await rpc.sendTransaction(tx, "passthrough");
  console.log(`txHash is : ${txHash}`)
}
```

### Advanced: Checking Alice's token balance
// todo

### Appendix
Mainnet(Lina)
* CKB Node RPC
    * mainnet.ckbapp.dev
* CKB Indexer RPC
    * mainnet.ckbapp.dev/indexer
* Mercury RPC
    * mercury-mainnet.ckbapp.dev

Testnet(Aggron)
* CKB Node RPC
    * testnet.ckbapp.dev
    * testnetrpc.ckb.dev
* CKB Indexer RPC
    * testnet.ckbapp.dev
    * testnetrpc.ckbapp.dev/indexer
* Mercury RPC
    * mercury-testnet.ckbapp.dev

 -
