### ISSUE TITLE
[idea] Transaction validator for P2PKH signing message

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#397]
## Motivation

The CKB contract is very flexible and can theoretically support any form of HMAC, so it can support signature verification on any blockchain in CKB, therefore, CKB can use other blockchain wallets as CKB's wallet, e.g. [Ethereum](https://github.com/nervosnetwork/lumos/tree/develop/examples/omni-lock-metamask) / [Cardano](https://github.com/nervosnetwork/lumos/tree/develop/examples/cardano-lock-namiwallet) etc. 

The user experience of these wallets is excellent, the transaction will be displayed when signing. For example, when we transfer ERC20, MetaMask will show the recipient address, type of the token and token amount, this is because MetaMask is able to recognize ERC20 transactions. However, MetaMask doesn't recognize CKB's transactions, so we can only use an API like `personal_sign` to sign the hashed transaction. The hashed transactions are unreadable for humans.

## Idea

We can provide a `validateSigningMessage` method to check `diget == hash(tx | witness)`, this helps the user to verify that a transaction is tampered.

```ts

type HashAlgorithm = 
  | 'ckb-blake2b-256'
  | 'ckb-blake2b-160' 
  | 'sha256' 
  | 'ripemd-160' 
  | 'sha3'
  | '...'
  | ((message: BytesLike) => Uint8Array);

interface Preimage {
  rawTransaction: RawTransaction;
  // witness
  additionalPayload: BytesLike;
}

declare function validateSigningMessage(
  preimage: Preimage,
  messageForSigning: BytesLike,
  options?: {
    hashAlgorithm: HashAlgorithm;
  }
): boolean

```

### Wallet gateway

```ts
// TODO a wallet gateway
type SignatureAlgorithms = 
  | 'eth_personal_sign' 
  | 'eth_signTypedData_v4' 
  | 'cardano_personal_sign'
  | '...';

type PubkeyLike =
  // public key 
  | BytesLike 
  // public key hash
  | { hashAlgorithm: HashAlgorithm, pubkeyHash: BytesLike }
```

### Todo - Explain `additionalPayload`

**Comment by IronLu233** [comment]
I do some investigation for this.

We can call the `EC.validate` method from package ''elliptic".

The supported algorhtim is:
- secp256k1
- p192
- p224
- p256
- p384
- p521
- curve25519
- ed25519

I have a question. the message for signing is meanning the sigend message from Metamask? 

And recoverableSignature is the signed message by Metamask?

**Comment by IronLu233** [comment]
# Hash the raw transaction with payload

``` ts
# need raw transaction and additonal payload
const withHashedTransaction = helpers.prepareSigningEntries(createTransactionSkeleton({ rawTransaction, witness: extraPayload.map(/* 
maybe map something */) }))

const unsignedMessage = withHashedTransaction.signingEntries(withHashedTransaction, 'secp256k1');

if (withHashedTransaction.signEntries[0].message !== messageForSigning) {
   return false;
}

const ec = EC('secp256k1')
return ec.validate(unsignedMessage, signature, pubkeyLike);
```
We can refactor the prepareSigningEntries for support other hasher.
``` ts
prepareSigningEntries(transaction: Transaction, hashAlgorithm: HashAlgorithm)
```

**Comment by IronLu233** [comment]
But I think `messageForSigning: BytesLike` should be `messageForSigning: BytesLike[]`, because in https://github.com/nervosnetwork/ckb-system-scripts/wiki/How-to-sign-transaction
we can see the signing message digest size is equals input group size
