### ISSUE TITLE
transfer Lumos to ckb-js org

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#401]
[ckb-js](https://github.com/ckb-js) org will be a collection of JavaScript-based toolkit for CKB. 
The target users of Lumos are JavaScript developers, and we will migrate Lumos to ckb-js org.

> GitHub will auto redirect the repo to the new URL after the repo is transferred, so we should avoid creating a new Lumos repo under nervosnetwork org

Before the transfer, we need to

- [x] create a branch and replace the GitHub repo URL from `nervosnetwork/lumos` to `ckb-js/lumos` in Lumos

After the transfer, we need to

- [x] Codecov is working correctly
- [x] Checking the CI is working correctly
- [x] Migrate the website
- [x] Enable GitHub project to manage Lumos

**Comment by PainterPuppets** [comment]
need to reconnect the git repo link on vercel
<img width="1228" alt="Conneoted Oin Reposilory" src="https://user-images.githubusercontent.com/22258327/189895529-bf76551a-d9b7-497d-976e-ad7d64dc3ee8.png">

**Comment by homura** [comment]
> need to reconnect the git repo link on vercel

done

**Comment by homura** [comment]
done to close
