### ISSUE TITLE
[feature request] Parsing molecule schema to codec directly

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#402]
## Motivation

As a dApp developer, i often explore some transactions in the ckb explorer to learn how a dApp works, but the `script.args`/`cell.data`/`transaction.witness` in the ckb explorer is serialized and represented as a hex string, most of this data is serialized from molecule. It would be very helpful to have a tool that would allow me to input the schema and these hex strings for decode, so I could understand the transaction

## How

We can offer a new API

```ts
type CodecRecord = Record<string, AnyCodec>;

declare function parseMolecule<
  Ref extends CodecRecord = CodecRecord, 
  Ret extends CodecRecord = CodecRecord
>(
  // molecule schema string
  mol: string, 
  // referenceable codec for mol, e.g. codecs.numbers, base.blockchain
  options?: { refs: Ref }
): Ret:
```

```ts
// language=molecule
const mol = `
array RGB (Uint8, 3);

struct Styled {
  background: RGB,
  color: RGB,
}
`;

import { number } from '@ckb-lumos/codec'

const codecs = parseMolecule(mol, { references: ...number /* referenceable codecs */})
```

After implement, we can offer a toolkit on the Lumos website to helps user to decode molecule binary

<img width="688" alt="image" src="https://user-images.githubusercontent.com/7511174/188324976-9d863402-83f1-4bfc-97c7-4861172942c7.png">

**Comment by homura** [comment]
the parser is WIP here https://github.com/zhangyouxin/mol-parser-ts and online preview is enabled at https://mol-parser-ts.vercel.app/

**Comment by zhangyouxin** [comment]
Now the parser is enabled to preview at: https://mol-parser-ts.vercel.app/

When I was trying to integrate the molecule parser in lumos website, there is an error occurred, I spent a long time trying to solve this error, but to no avail.


Screenshot of the problem：

![image](https://user-images.githubusercontent.com/3870972/190539300-4bb73499-0a3e-41c3-9e2c-35e5a1041a32.png)


PR： https://github.com/ckb-js/lumos/pull/413
Code： https://github.com/zhangyouxin/lumos/tree/molecule

Steps to reproduce：

```sh
# checkout code
git remote add zhangyouxin-lumos git@github.com:zhangyouxin/lumos.git
git fetch zhangyouin-lumos
git checkout zhangyouxin-lumos/molecule

# build lumos
yarn install --force
yarn clean
yarn build

# launch website on local machine
cd website
# yarn start works fine, visit http://localhost:3000/tools/molecule-parser to try it out.
# produces problem below
yarn build
yarn serve
```

Then visit http://localhost:3000/tools/molecule-parser and open the console to check the problem.


I have also tried to integrate this tool in CRA before, and it works, so I guess there is a Dodusaurus-related problem, preview at https://mol-parser-ts.vercel.app/ 

- CRA code: https://github.com/zhangyouxin/mol-parser-ts
- preview: https://mol-parser-ts.vercel.app/

Is there anyone who can help me with this problem?

The attempts that I have made：

1. remove `packages/molecule/grammar/mol.js` （no help）
2. remove these lines of code：https://github.com/zhangyouxin/lumos/blob/molecule/website/src/components/molecule-parser/Molecule.tsx#L55-L65 （this action resolves the problem, but business requirements not met）
3. change `website/tsconfig.json`: （no help）
  ```json5
    // ...
    compilerOptions: {
      // ...
      "esModuleInterop": false
    }
  ```

**Comment by zhangyouxin** [comment]
Thanks to @IronLu233 , using `escape-string-regexp` lib to replace https://github.com/ckb-js/lumos/blob/09bd023b1cecb62e377b559770a4c3776ec50b36/packages/codec/src/utils.ts#L15 and https://github.com/ckb-js/lumos/blob/09bd023b1cecb62e377b559770a4c3776ec50b36/packages/codec/src/utils.ts#L38 solved my problem.

This problem is caused by Ducurasaus when adding a CJS module that contains tagged templates to the dependencies list.

**Comment by homura** [comment]
website integration has started at https://github.com/ckb-js/lumos/issues/415
