### ISSUE TITLE
Support the light client

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#438]
**Is your feature request related to a problem? Please describe.**

[ckb-light-client](https://github.com/nervosnetwork/ckb-light-client) is a light client for CKB that allow users to sync data from only the scripts they care about. Compare to full node, it will 

- sync faster
- reduce the disk usage

**Describe the solution you'd like**

TODO

**Additional context**

- [ckb-light-client](https://github.com/nervosnetwork/ckb-light-client)

**Comment by PainterPuppets** [comment]
### light client rpc analysis

exist in rpc
`send_transaction `	missing `verbosity` param
`get_tip_header`		missing `verbosity` param
`get_header`			missing `verbosity` param
`get_transaction`		missing `verbosity` param

exist in ckb-indexer rpc: `get_cells`, `get_transactions`, `get_cells_capacity`

new rpc
`fetch_header`		(block_hash: h256)
`remove_headers`		(block_hashes?: vec<h256>)
`fetch_transaction`	(tx_hash: h256)
`remove_transactions`	(tx_hashes: vec<h256>)
`get_scripts`			(): {script, block_number: hexnumber}
`set_scripts`			(script: script, block_number: hexnumber)


### How to support the light client in the `lumos`

#### plan 1: change ckb indexer for support light client
```ts

export interface IndexerRpc {
  getTip(): Promise<Tip>;
  getCells<WithData extends boolean = true>(
    searchKey: GetCellsSearchKey<WithData>,
    order: Order,
    limit: HexString,
    cursor?: string
  ): Promise<GetLiveCellsResult<WithData>>;
  getTransactions<Grouped extends boolean = false>(
    searchKey: GetTransactionsSearchKey<Grouped>,
    order: Order,
    limit: HexString,
    cursor?: string
  ): Promise<IndexerTransactionList<Grouped>>;
}

```
``` diff
// ckb-indexer.ts

export class CkbIndexer implements Indexer {
-   constructor(public ckbIndexerUrl: string, public ckbRpcUrl: string) 
+   constructor(indexerRpc: IndexerRpc | string, ckbRpc: RPC | string)  
}
```
```ts
// usage
import { Indexer, lightClientRpc } from '@ckb-lumos/ckb-indexer'
import { RPC } from '@ckb-lumos/rpc'

const rpc = new RPC('xxx');
const lightClientRpc = new lightClientRpc('xxxxx');
lightClientRpc.setScripts({...});
const indexer = new Indexer(lightClientRpc, rpc)
```

#### plan 2: add indexerFactory & lightClientIndexer
```ts
// usage
import { IndexerFactory } from '@ckb-lumos/ckb-indexer'

const indexerRpcUrl = 'xxx';
const rpcUrl = 'xxx';
const lightClientRpcUrl = 'xxx';

// ckb-indexer
const indexer = IndexerFactory.getIndexer({ indexerRpcUrl,  ckbRpcUrl: rpcUrl })

// merged indexer
const indexer = IndexerFactory.getIndexer({ indexerRpcUrl: rpcUrl,  ckbRpcUrl: rpcUrl })

// light client indexer
const indexer = IndexerFactory.getIndexer({ indexerRpcUrl: lightClientRpcUrl,  ckbRpcUrl: rpcUrl,  })
```

#### task list
 - implement `LightClientRpc` class

**Comment by homura** [comment]
vote for "plan 1: change ckb indexer for support light client"

but we need https://github.com/ckb-js/lumos/issues/443 at first
