### ISSUE TITLE
Indexer / Collector need to be refactored

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#443]
**Is your feature request related to a problem? Please describe.**

The native indexer is no longer needed for lumos, so this `interface indexer` is outdated and these `start`, `stop`, `startForever` and other methods are no longer needed

Both `Indexer` and `CellProvider` provide the same functionality for constructing `CellCollector`, and we should unify them to avoid confusing developers with the same functionality being implemented multiple times

https://github.com/ckb-js/lumos/blob/b1f10534272e12eebebcd40da85b7d4622bd22f8/packages/base/src/indexer.d.ts#L37-L40

https://github.com/ckb-js/lumos/blob/b1f10534272e12eebebcd40da85b7d4622bd22f8/packages/base/src/indexer.d.ts#L57-L70

**Describe the solution you'd like**

Maybe we can just keep `CellProvider` and deprecated `interface Indexer`, so that after refactor we can have a different implementation based on `CellProvider`, which can be 
- `DefaultCellProvider` with CKB's RPC
- `CkbIndexerProvider` with ckb-indexer's RPC 
- `LightClientCellProvider` with ckb-light-client's RPC

**Comment by PainterPuppets** [comment]
## How refactor

``` ts
export interface GetCellProvider {
  getCells<WithData extends boolean = true>(
    searchKey: GetCellsSearchKey<WithData>,
    order: Order,
    limit: HexString,
    cursor?: string
  ): Promise<GetLiveCellsResult<WithData>>;
}
```

1. refactor `CKBCellCollector`,  only dependent to `GetCellProvider`
2. change `CkbIndexer` as extends from `CkbCellCollector`
