### ISSUE TITLE
Error: process is not defined in manager.ts

### ISSUE THREAD

**Issue by IronLu233** [nervosnetwork/lumos#446]
**Describe the bug**

**To Reproduce**

1. Use Vite to bundle `@ckb-lumos`
2. call `initializeConfigLegacy` from `@ckb-lumos/config-manager`
3. run the app, and browser throw an error
![image](https://user-images.githubusercontent.com/20639676/195796040-99578f98-d1f1-4672-9db6-315b122a7d57.png)

**Expected behavior**
Should works well.
**Screenshots**

![image](https://user-images.githubusercontent.com/20639676/195796040-99578f98-d1f1-4672-9db6-315b122a7d57.png)

**Additional context**

the code should use `typeof process !== undefined` before use global variable process

**Comment by homura** [comment]
Close the issue due to inactivity, and this is a deprecated method, we should avoid continuing to use this method, checking the process is not helpful and throwing this error will prevent the program from running in the browser
