### ISSUE TITLE
[Bug] `@ckb-lumos` packed it's dependencies source code and cause multiple module instance when import from diffierent entries

### ISSUE THREAD

**Issue by IronLu233** [nervosnetwork/lumos#448]
**Is your feature request related to a problem? Please describe.**

I found there are two `config-manager` when I run the code.
``` typescript
import { config } from '@ckb-lumos/lumos'
import * as config2 from '@ckb-lumos/config-manager';

const AGGRON4 =config.predefined.AGGRON4;
// set the config in '@ckb-lumos/lumos';
config.initializeConfig(AGGRON4);

// get the config from config-manager package
config2.getConfig(); // return LINA, not AGGRON4
config2.getConfig() !== config.getConfig() // they are not same
```

**Describe the solution you'd like**
The package named `@ckb-lumos/lumos` should not include other packages' source code(eg. `@ckb-lumos/config-manager`).

But there are a special case, that we need include the dependencies source code. it's when we want bundle a browser package(use iife, and user call lumos API via `window.lumos`); we can provide a special package for browser.

But in most other case. we don't pack the dependencies source code into `@ckb-lumos/lumos`, just let the bundler, like Webpack, to resolve the package dependencies, and other packages into one.

**Describe alternatives you've considered**

1. Always import the API in `@ckb-lumos/lumos`; Only import it from ”`@ckb-lumos/others`“;'
2. Never import API from `@ckb-lumos/lumos`; Only import it from `@ckb-lumos/others`;'

**Additional context**

![image](https://user-images.githubusercontent.com/20639676/196967489-ee944eba-168a-4ebd-a30d-9536dce2062b.png)
There a funcion named `getConfig` in `@ckb-lumos/lumos` bundle.

**Comment by IronLu233** [comment]
To resolve this problem, we need change the build process in our project.
I did some research and in conclution:
1. If we bundle submodule(eg. `@ckb-lumos/codec`) into one js file, the import approach like `import Module from '@ckb-lumos/codec/lib/something'` can not available anymore.
2. If we do not bundle the source code, just transform it to js file. we can not polyfill node native modules(like`buffer`) in subpackage
3. If we confirm our library always runs in a polyfilled environment(Our library user use webpack and babel) or in NodeJS, we have no need to use Babel, just use Typescript's `tsc`  is enough. For example, [React does not use preset-env in it's Babel's config](https://github.com/facebook/react/blob/main/babel.config.js#L5)
4. Rollup may be a better library bundler because it's generated code is smaller, and takes better support for es module

**Comment by IronLu233** [comment]
A rollup config seems like
``` typescript
import { defineConfig } from "rollup";
import commonjs from "@rollup/plugin-commonjs";
import { getBabelOutputPlugin } from "@rollup/plugin-babel";
import typescript from "@rollup/plugin-typescript";

export default defineConfig([
  {
    input: "src/index.ts",
    plugins: [commonjs(), typescript()],
    output: [
      {
        format: "esm",
        file: "./dist/index.js",
        plugins: [getBabelOutputPlugin({ presets: ["@babel/preset-env"] })],
        sourcemap: true,
      },
      {
        format: "cjs",
        file: "./dist/index.cjs",
        plugins: [getBabelOutputPlugin({ presets: ["@babel/preset-env"] })],
        sourcemap: true,
      },
    ],
    external: (id) => id.includes("@ckb-lumos"),
  },
]);
```
It can generate commonjs and es module bundle with Typescript definition file.（I use it to build my another library project : )
![image](https://user-images.githubusercontent.com/20639676/197188217-2ab03cad-6d72-404d-b98a-081538e44cb0.png)

**Comment by IronLu233** [comment]
# The [ethers.js](https://github.com/ethers-io/ethers.js/tree/master) build solution
## subpackage build
it use typescript project reference, when run `tsc -build` in package root, each subpackage will be built by tsc
https://www.typescriptlang.org/docs/handbook/project-references.html
## ESM and CJS module build in subpackages
there are some scripts in misc, and a script named `setupConfig`
It will override config of `tsconfig.json` on disk.

After config modify, the tsc will build source code with ESM and CJS.

## Node.JS API shimming
The NodeJS API shimming is just when use `@ethers/shim` or use umd in browser directly enabled. In other cases(Use Webpack or other bundler), it need the user add shim manually.

**Comment by IronLu233** [comment]
I think there are three demands
1. Support code works well on browser, although it uses some NodeJS API(lile crypto)
2. Allow user import submodule private API via `import { } from '@lumos/codec/lib/somethingPrivate'`
3. When user use Webpack or other bundler, whether he import the module from `@lumos/lumos` or `@lumos/config-manager`, their reference are same.

The demand `3` we have to satisfy it because it cause this issue, but `1` and `2`, we can not satisfy both of them.

if we choose `1`, the solution is:
- build the code of subpackage with rollup, with different config, we provide two entries in each subpackage. the `"browser"` field of `package.json` refers a node API shimed entries, and the "module" and "main" with normal entries
- the `@ckb-lumos/lumos` package just use `export * as config from '@ckb-lumos/config-manager'`
- user doesn't need shim  Node API when they want use lumos on browser with their own bundler.
- user can't use `import {} from '@lumos/codec/lib/somethingPrivate'`

Pros:
- user don't need shim Node API, they can directly use it in browser with their build toolchian
CONS
- If we release these change, they can not import private API, but the Typescript type definition is not affected.

if we choose `2` the solution is:
- build the code of subpackage with our origin build tools(Babel for `.js` file and tsc for`.d.ts` at sametime)
- set the dependency of `@ckb-lumos/lumos` as external package, do not include their source code into bundle
- tell user they should shim NodeJS API

Pros
- less changes for build tools. we just set subpackages as external module in webpack
CONS:
- when the change publish, our user need to shim Node API on their own bundler

**Comment by homura** [comment]
can you please add the tips for how the changes will affect lumos user, how much migration work do users need to do for these changes?

**Comment by IronLu233** [comment]
> can you please add the tips for how the changes will affect lumos user, how much migration work do users need to do for these changes?

For options1, lumos user should modify their code
``` ts
// should change this code
import { Config } from '@ckb-lumos/config-manager/lib/configManager';
// to
import { config } from '@ckb-lumos/lumos';
type ConfigManager = config.ConfigManager;
// or
import { ConfigManager  } from '@ckb-lumos/config-manaer';
```
And this is all of user's change.

For option 2
user should config their Webpack or other build tools like [this gist](https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a). After this done, they don't change their source code.

For new user, he/she should polyfill the  NodeJS API shimming first

**Comment by homura** [comment]
Upvote for option 2, which makes more sense because lumos does have some sub-packages available for NodeJS only, such as `@ckb-lumos/debugger`, etc.

lumos can still keep `lumos.min.js` for the browser environment, but when publishing, lumos does not need to add `lumos.umd.js` to the "browser" in `package.json`

---

And for current lumos, we should tip developers

- recommend using only `@ckb-lumos/lumos` in a project
- Do **NOT** mix `@ckb-lumos/lumos`'s config and `@ckb-lumos/config-manager`, because `@ckb-lumos/config-manager` is stateful

**Comment by IronLu233** [comment]
> Upvote for option 2, which makes more sense because lumos does have some sub-packages available for NodeJS only, such as `@ckb-lumos/debugger`, etc.
> 
> lumos can still keep `lumos.min.js` for the browser environment, but when publishing, lumos does not need to add `lumos.umd.js` to the "browser" in `package.json`
> 
> And for current lumos, we should tip developers
> 
> * recommend using only `@ckb-lumos/lumos` in a project
> * Do **NOT** mix `@ckb-lumos/lumos`'s config and `@ckb-lumos/config-manager`, because `@ckb-lumos/config-manager` is stateful

And should we update the document for telling user use the NodeJS shiming?

**Comment by homura** [comment]
> And should we update the document for telling user use the NodeJS shiming?

Yeah, I think it is needed
