### ISSUE TITLE
type definition and the implementation are different on package `@ckb-lumos/base`

### ISSUE THREAD

**Issue by IronLu233** [nervosnetwork/lumos#449]
**Describe the bug**

When I browse the code in `base` package, I found some API's implement are not fits it's Typescript definition.

For example:

https://github.com/ckb-js/lumos/blob/1fd1772b43fa710dc983d1a44e280af4457bac0a/packages/base/src/values.js#L27-L31

but in it's `values.d.ts` file, the difinition is:

https://github.com/ckb-js/lumos/blob/1fd1772b43fa710dc983d1a44e280af4457bac0a/packages/base/src/values.d.ts#L12-L14

**To Reproduce**

None, this is the codebase bug.
**Expected behavior**

the difinition and it's 
**Screenshots**

**Additional context**

This situation also appers in https://github.com/ckb-js/lumos/blob/develop/packages/base/src/utils.js and [indexer.d.ts
](https://github.com/ckb-js/lumos/blob/develop/packages/base/src/indexer.js)

**Comment by homura** [comment]
the second parameter `options` can be markded as deprecated

**Comment by IronLu233** [comment]
https://github.com/ckb-js/lumos/blob/develop/packages/base/src/indexer.js#L89
And how about this code, the h even not defined in it's context🤣
``` ts

  async *collect() {
    let hashes = await this.getTransactionHashes();
    for (const hash of hashes) {
      const tx = await this.rpc.get_transaction(hash);
      if (!this.skipMissing && !tx) {
        throw new Error(`Transaction ${h} is missing!`);
      }
      if (this.includeStatus) {
        yield tx;
      } else {
        yield tx.transaction;
      }
    }
  }
}
```

**Comment by IronLu233** [comment]
> https://github.com/ckb-js/lumos/blob/develop/packages/base/src/indexer.js#L89 And how about this code, the h even not defined in it's context🤣
> 
> ```ts
>   async *collect() {
>     let hashes = await this.getTransactionHashes();
>     for (const hash of hashes) {
>       const tx = await this.rpc.get_transaction(hash);
>       if (!this.skipMissing && !tx) {
>         throw new Error(`Transaction ${h} is missing!`);
>       }
>       if (this.includeStatus) {
>         yield tx;
>       } else {
>         yield tx.transaction;
>       }
>     }
>   }
> }
> ```

It seems the `hash` variable.
