### ISSUE TITLE
The Address Conversion tool is broken.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/lumos#455]
The [address conversion tool](https://lumos-website.vercel.app/tools/address-conversion) is no longer working. A Javascript error is received on page load.

![20221106183715](https://user-images.githubusercontent.com/37931/200214991-449201ff-fb98-4bd4-ae81-386151dcf89b.png)

**Comment by homura** [comment]
Thank you for your report, we are investigating the error and will fix it as soon as possible
