### ISSUE TITLE
Collecting cells from more than one script

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#470]
**Is your feature request related to a problem? Please describe.**

The programming model of CKB is UTxO, for UTxO wallets, they often derive many keys, which often correspond to different lock scripts, that is, the wallets often need to collect cells with more than one lock. But the current `CellCollector` only supports a single script filter, if lumos support for multiple scripts, it will be convenient for collecting cells with multiple locks

**Describe the solution you'd like**

Maybe we can enhance the `CellCollector` to archive this

```ts
const collector = new CellCollector(rpc, [
  { lock: lock1, ... },
  { lock: lock2, ... },
  { lock: lockn, ... },
])

for await (const cell of collector.collect()) {
  ...
}
```

simply says, we can enhance the CellCollector's constructor second param, change it to `CKBIndexerQueryOptions | CKBIndexerQueryOptions[]` https://github.com/ckb-js/lumos/blob/437b641279317a70abc5dd4d0f4790455c13aa61/packages/ckb-indexer/src/collector.ts#L25-L30

**Comment by zhb666** [comment]
Scheme 1: Change the type of receiving parameters, judge the parameters at the bottom layer, and process in a loop
[https://github.com/zhb666/lumos/commits/feature/collect-ells](https://github.com/zhb666/lumos/commit/9ae39719b9681778cd9daf18633dba77a430cae6)

**Comment by zhb666** [comment]
Solution 2: Process the parameters at the entry of CellCollector. After a single Query is iterated, continue to iterate the next Query?
```js
if (Array.isArray(query)) {
  for (query ) {
    const collector = new CellCollector(query);
    for await  ( let cell of collector.getLivceCell()) {
        ...
    }
  }
}
```

**Comment by zhb666** [comment]
Can getLiveCell be returned as a collection?
[https://github.com/zhb666/lumos/blob/feature/collect-ells/packages/ckb-indexer/src/collector.ts#L178-#L213](https://github.com/zhb666/lumos/blob/feature/collect-ells/packages/ckb-indexer/src/collector.ts#L178-#L213)

**Comment by homura** [comment]
> Can getLiveCell be returned as a collection?

can you provide more context of your question? Like this, I want to update API of `getLiveCell`, because I think ...

```diff
- function getLiveCell(...): Promise<GetCellResult>;
+ function getLiveCell(...): Promise<Collection>;
```
