### ISSUE TITLE
Outdated RPC methods

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#471]
**Is your feature request related to a problem? Please describe.**

CKB [0.106.0](https://github.com/nervosnetwork/ckb/issues/3710) has been released, there are [some changes](https://github.com/nervosnetwork/ckb/issues/3726) Lumos should care about

**Describe the solution you'd like**

-  `get_block_filter`
-  `get_transaction_and_witness_proof`
-  `verify_transaction_and_witness_proof`
-  `get_fork_block`
-  `get_block_median_time`
-  `estimate_cycles`
-  `get_fee_rate_statics`
-  `get_fee_rate_statistics`

**Comment by IronLu233** [comment]
Most work is finished, but I have some problem on testing and verifying the APIs.
I have some question for these API:
- what is the forked block?
-  How to check the return value of `verify_transaction_and_witness_proof`?
- How to test `estimate_cycles`? Can I just invoke it in e2e and check the API return value's type is a number?

**Comment by homura** [comment]
> what is the forked block?

~~Maybe it means which block the CKB has forked, e.g. Lina -> Mirana? I'm giving some answers to this question semantically, but I'm not sure what exactly you mean "fork"~~

Sorry, I lost some context, I noticed you might be asking about [this](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md#method-get_fork_block)?

> How to check the return value of `verify_transaction_and_witness_proof`?
> How to test estimate_cycles? Can I just invoke it in e2e and check the API return value's type is a number?

The two questions above are similar. I suggest we keep the same style as current [`@ckb-lumos/rpc`](https://github.com/ckb-js/lumos/tree/e73ca0502b0feb3e98be848f76325a912052d0f0/packages/rpc/__tests__/formatters) for now, and we can open another issue to discus if we need to test RPC in E2E. E2E is a bit different with the current test set.

**Comment by IronLu233** [comment]
> suggest we keep the same style as current [@ckb-lumos/rpc](https://github.com/ckb-js/lumos/tree/e73ca0502b0feb3e98be848f76325a912052d0f0/packages/rpc/__tests__/formatters) for now


Seems we should mock the RPC network API and check the inputs and outputs for invoking.

**Comment by homura** [comment]
> Seems we should mock the RPC network API and check the inputs and outputs for invoking.

I prefer to keep it simple and just use the `params` and the `result` from the RPC [docs](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md) as test vectors

```json
{
  "toTransactionAndWitnessProof": [
    {
      "result": {
        "block_hash": "0x7978ec7ce5b507cfb52e149e36b1a23f6062ed150503c85bbf825da3599095ed",
        "transactions_proof": {
          "indices": ["0x0"],
          "lemmas": []
        },
        "witnesses_proof": {
          "indices": ["0x0"],
          "lemmas": []
        }
      },
      "expected": {...}
    }
  ]
}

```

**Comment by homura** [comment]
@IronLu233 how's the issue going?

**Comment by IronLu233** [comment]
### The PR is ready.
I met a very awful  bug on unit test. If the unit test fails, it will always throw the error. No any extra content except `RangeError: Maximum call stack size exceeded`
![image](https://github.com/ckb-js/lumos/assets/20639676/9aadcc0c-1df6-474f-b105-803c69c90545)
It slows my test developing.
I can not solve the problem, and use breakpoint to accomplish these tests.
This bug exists on JS unit test, and seems a internal bug in jest.  However, although I update it, still remain.
https://github.com/ckb-js/lumos/blob/develop/packages/rpc/__tests__/ckb-rpc.test.js#L2015
