### ISSUE TITLE
[light-client] added new `get_peers` / `local_node_info` and updated `fetch_transaction` / `get_transaction` / `set_scripts`

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/lumos#474]
https://github.com/nervosnetwork/ckb-light-client/pull/123
https://github.com/nervosnetwork/ckb-light-client/pull/110
https://github.com/nervosnetwork/ckb-light-client/pull/108

- [x] add `get_peers`
- [x] add `local_node_info`
- [x] update `fetch_transaction`
- [x] update `get_transaction`
- [x] update `set_scripts`

**Comment by homura** [comment]
hold on, there are still some changes pending

**Comment by homura** [comment]
The light-client was released, now the issue can be started

**Comment by homura** [comment]
[ckb-light-client@0.3.0](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.0) has been released, and the light client protocol also has been launched on the CKB mainnet. It's time to update the relevant light client modules in Lumos. To make tests independent and reproducible, it's recommended to create fixtures like [`@ckb-lumos/rpc`](https://github.com/homura/lumos-experimental/blob/1c331530f1b5075fc8d4d7d9b81de13be818edfb/packages/rpc/__tests__/formatters/params.fixtures.json)

**Comment by PainterPuppets** [comment]
> [ckb-light-client@0.3.0](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.0) has been released, and the light client protocol also has been launched on the CKB mainnet. It's time to update the relevant(相关) light client modules in Lumos. To make tests independent and reproducible, it's recommended to create fixtures like [`@ckb-lumos/rpc`](https://github.com/homura/lumos-experimental/blob/1c331530f1b5075fc8d4d7d9b81de13be818edfb/packages/rpc/__tests__/formatters/params.fixtures.json)

The `fixtures` in the `rpc` module is suitable for unit tests that test serialized params and results, where the expected inputs and expected outputs are clear. `light-client-rpc` currently only does e2e testing, and the use of fixtures feels a bit inappropriate

**Comment by homura** [comment]
> The `fixtures` in the `rpc` module is suitable for unit tests that test serialized params and results, where the expected inputs and expected outputs are clear. `light-client-rpc` currently only does e2e testing, and the use of fixtures feels a bit inappropriate

I am not very sure what you mentioned about the difference between the light client and RPC. As I see it, both need to prepare returned data from the node and define the expected data for client

**Comment by PainterPuppets** [comment]
> > The `fixtures` in the `rpc` module is suitable for unit tests that test serialized params and results, where the expected inputs and expected outputs are clear. `light-client-rpc` currently only does e2e testing, and the use of fixtures feels a bit inappropriate(不当)
> 
> I am not very sure what you mentioned about the difference between the light client and RPC. As I see it, both need to prepare returned data from the node and define the expected data for client

The rpc module use `fixtures` to test the `toParams` and `toResult` functions, these functions are responsible for converting snake case and camel case.

and the tests for direct interaction with rpc nodes are also in the`e2e-test` module

There seems to be a lot of test in `e2e-test` that is dynamic and contextual, such as commit a transaction and then testing to see if the `fetch_transaction` rpc is working properly based on the `txHash`

I'm probably not sure how to put this contextual logic into fixtures, any ideas?

**Comment by homura** [comment]
> There seems to be a lot of test in e2e-test that is dynamic and contextual

Exactly, e2e is contextual, we need a lot of effort to construct a case, and this is the reason that I recommend introducing unit cases without context for the light client module.

> I'm probably not sure how to put this contextual logic into fixtures, any ideas?


Regarding your question about how to implement contextual logic into fixtures, I suggest following the example of using `get_transaction`. We can define the expected and actual results in a JSON format, and check them against each other.

```json5
{
  "toTransaction": {
    "actual": "...",
    "expected": "...",
  }
}
```

However, the current light client module just deep-camelized the RPC's result without any check or type definition, this is a lack of transparency and easily lead to bugs. 

I realize that the light client's data structures are the same as the `ckb-types`, we can reuse the `ResultFormatter` from `@ckb-lumos/rpc` directly, such as the `TransactionWithStatus`. This way, we don't need to reconstruct the format cases here and improve the module's quality

**Comment by homura** [comment]
@gpBlockchain `light-client@0.3.0` has been adapted in `@ckb-lumos/light-client`, can you help to try it again?

```sh
npm install @ckb-lumos/light-client@ckb2023
```
