### ISSUE TITLE
Collecting transactions from multiple queries

### ISSUE THREAD

**Issue by IronLu233** [nervosnetwork/lumos#482]
**Is your feature request related to a problem? Please describe.**

A HD wallet keeps a set of private key, and it means the wallet user can unlock the cell locked by these keys. When we recovery from 
 mnemonics, the wallet use it's key derivation logic to recovery the private keys.

the recovery process will stop when the program find there are N empty private key(in CKB, it maps to lock script). So if `transactionCollector` support multiple queries, the wallet developer can write cleaner code for key derivation recovery. 

**Describe the solution you'd like**

Let the second parameter of CKBIndexerTransactionCollector's constructor support an `CKBIndexerQueryOptions` array
``` ts
class CKBIndexerTransactionCollector {
  constructor(indexer: CKBIndexer, queries: CKBIndexerQueryOptions[] | CKBIndexerQueryOptions, CKBRpcUrl: string, options)
}
```

**Comment by homura** [comment]
This is a good idea, but multiple QueryOptions will not be compatible with the indexer's cursor because the indexer's cursor is one-to-one with the QueryOption, so maybe we can use chunk + batch as a more appropriate way
