### ISSUE TITLE
Support Chained Transactions

### ISSUE THREAD

**Issue by zhangyouxin** [nervosnetwork/lumos#501]
## Motivation

https://talk.nervos.org/t/non-blocking-chained-transaction-and-its-applications-in-ckb/6649

In order to provide a more smooth experience for developer/dapp user to send transactions in sequence, we need to collect freshly created pending cells created by recent transactioins, although they are still in memPool.

## What can we do to support it

To achieve the purpose of this issue described in motivation, we need to implement:

- ckb-indexer filter protocol, see the `search_key`, `limit`, `order` and `after` in [get_cells rpc](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md#method-get_cells)
- transaction manager to manage new created transaction outputs and inputs

What we need to do:

- [ ] implement ckb-indexer filter protocol in @ckb-lumos/ckb-indexer
- [ ] refactor the current cell collector to use the filter
- [ ] the @ckb-lumos/transaction-manager is too old, create a new transaction-manager with reasonable API

**Comment by homura** [comment]
update: after the discussion, we found that we can update the existing [`TransactionManager`](https://github.com/ckb-js/lumos/blob/develop/packages/transaction-manager/index.d.ts) to handle the pending cells

```diff
+ interface CkbIndexerCellProvider {
+    collector(query: CkbIndexerQueryOptions): { collect(): AsyncIterator<Cell> }
+ }

declare class TransactionManager {
  constructor(
-   indexer: Indexer,
+   // when a string is provided, it will be treated as a CKB RPC
+   indexer: CkbIndexerCellProvider | string
    options?: {
      logger?: logger.Logger;
      pollIntervalSeconds?: number;
      storage?: AsyncStorage;
    }
  );

  start(): void;

  stop(): void;

  sendTransaction(tx: Transaction): Promise<Hash>;

  /**
   * If set `usePendingOutputs` to false, will not use pending outputs, default to true.
   *
   * @param queryOptions
   * @param options
   */
  collector(
-    queryOptions?: QueryOptions,
+    queryOptions?: CkbIndexerQueryOptions,
    options?: { usePendingOutputs?: boolean }
  ): CellCollector;
}


```

**Comment by zhangyouxin** [comment]
It's reasonable to change `indexer` to `CkbIndexerCellProvider | string`, also we need to pass in `rpcUrl` in constructor to make sure `TransactionManger` is able to:

- send transactions to rpc endpoint
- update stored transaction status


```diff
  constructor(
+   rpcUrl: string,
+   indexer: CkbIndexerCellProvider | string
    options?: {
      pollIntervalSeconds?: number;
      storage?: AsyncStorage;
+     usePendingCells?: boolean; //defaut to true
    }
  );
```

**Comment by homura** [comment]
> ```diff
>   constructor(
> +   rpcUrl: string,
> +   indexer: CkbIndexerCellProvider | string
>     options?: {
>       pollIntervalSeconds?: number;
>       storage?: AsyncStorage;
> +     usePendingCells?: boolean; //defaut to true
>     }
>   );
> ```

## The `rpcUrl` can be optional

I understand the `rpcUrl` is used to remove the pending cell when the corresponding transaction is committed, but "remove pending cells from list" is just nice to have, we can also remove the pending cell when the `collector.collect` collected the pending cell

## `usePendingCell` can be defined in `collector` 

Since developer may `usePendingCells` in collector-a but not in collector-b

**Comment by zhangyouxin** [comment]
But how about the second usage of `rpcUrl`? when calling `TransactionManager.prototypel.sendTransaction`, a `rpcUrl` endpoint is necessary to decide where to send the transaction to.

**Comment by homura** [comment]
> But how about the second usage of `rpcUrl`? when calling `TransactionManager.prototypel.sendTransaction`, a `rpcUrl` endpoint is necessary to decide where to send the transaction to.

Oh yes, `sendTransaction` is indeed necessary. Do you have any idea for this? Maybe multiple constructor?

```ts
// with a small breaking change
declare class TransactionManager {
  constructor(rpcUrl: string, options: {});
  constructor({cellProvider, transactionSender, ...otherOptions});
  constructor(urlOrOptions: string | Options, options?: Options) {
    // init here
  }
}
```
