### ISSUE TITLE
refactoring indexer query options

### ISSUE THREAD

**Issue by zhangyouxin** [nervosnetwork/lumos#508]
## Description

Now that Lumos has a [query options type](https://github.com/ckb-js/lumos/blob/26c3a45cac2bff1e4c4b08ca05472dcd6ebf6e39/packages/base/src/indexer.ts) for `Indexer`:

```ts
export interface QueryOptions {
  lock?: Script | ScriptWrapper;
  type?: Script | ScriptWrapper | "empty";
  // data = any means any data content is ok
  data?: string | "any";
  argsLen?: number | "any";
  /** `fromBlock` itself is included in range query. */
  fromBlock?: Hexadecimal;
  /** `toBlock` itself is included in range query. */
  toBlock?: Hexadecimal;
  skip?: number;
  order?: "asc" | "desc";
}

export interface ScriptWrapper {
  script: Script;
  ioType?: "input" | "output" | "both";
  argsLen?: number | "any";
}

```

And [`CkbInderQueryOptions`](https://github.com/ckb-js/lumos/blob/26c3a45cac2bff1e4c4b08ca05472dcd6ebf6e39/packages/ckb-indexer/src/type.ts#L20-L28) :

```ts
export interface CKBIndexerQueryOptions extends QueryOptions {
  outputDataLenRange?: HexadecimalRange;
  outputCapacityRange?: HexadecimalRange;
  scriptLenRange?: HexadecimalRange;
  bufferSize?: number;
  withData?: boolean;
  groupByTransaction?: boolean;
  scriptSearchMode?: ScriptSearchMode;
}
```

Some refactable points:

 - what is `ioType` used for in `ScriptWrapper`
 - `QueryOption` has a `argsLen` and `ScriptWrapper` and has a `argsLen`, which is redundant and confusing when both exists
 - why `toBlock` is sepecial to be inclusive,  we should follow ckb-indexer convention to be left-inclusive and right-exclusive
 - `data` could be `any`? since it is optional field, maybe just leave it undefined to express "anything in this field is accepted" , it's simpler this way.
 - same with `argsLen`
 - sicne `codeHash` and `hashType` has fixed length, so that `argsLen` has same functionality with `scriptLenRange`, maybe we can remove this field.

refactable points in implementation:

 - what does [argsLen set to -1](https://github.com/ckb-js/lumos/blob/26c3a45cac2bff1e4c4b08ca05472dcd6ebf6e39/packages/ckb-indexer/src/collector.ts#LL35C19-L35C19) mean? From the context we know it represents "any argsLen is accepted", maybe just leave it undefined.

Other thoughts:

Maybe some of the fields is for `lumos indexer` in history, but since lumos don't have it's own indexer service anymore, we could refactor this part. `QueryOptions` could align with [ckb indexer SearchKey](https://github.com/nervosnetwork/ckb/tree/develop/rpc#type-indexersearchkey) and [ckb indexer SearchKey Filter](https://github.com/nervosnetwork/ckb/tree/develop/rpc#type-indexersearchkeyfilter), and for more filtering functionality, we can have a `ExtendedQueryOptions` containing `data`, `dataLength` and other fields ckb-indexer doesn't have.

**Comment by homura** [comment]
This is resolved by #502
