### ISSUE TITLE
Outdated snake case doc examples

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#509]
Lumos@0.19 have a breaking change which changes the snake case API to camel case, but in the the documentation there are multiple uses of outdated snake API for multiple components.

[For example RPC examples](https://lumos-website-git-stable-cryptape.vercel.app/api/modules/rpc.html) still follow the snake case API:
```
import { RPC } from "@ckb-lumos/rpc"
const rpc = new RPC("http://localhost:8114");
await rpc.get_tip_header();

// Or provide an optional indexer param, if provided, will wait for sync after every RPC call.
const rpc = new RPC("http://localhost:8114", indexer)
await rpc.get_tip_header(); // before it return, will sync indexer to tip.
```

Keep up the great work :muscle:
Phroi

**Comment by homura** [comment]
The updated API is [here](https://lumos-website-git-stable-magickbase.vercel.app/api/)

**Comment by phroi** [comment]
Alright, let me give you a feedback on that then.

I don't believe [deleting the RPC examples is the right call](https://lumos-website-git-stable-magickbase.vercel.app/api/modules/rpc.html), on the other side I would improve what was there before and include more example material.

Moreover the issue of outdated docs examples is still present, see [ckb-indexer](https://lumos-website-git-stable-magickbase.vercel.app/api/modules/ckb_indexer.html) and [toolkit](https://lumos-website-git-stable-magickbase.vercel.app/api/modules/toolkit.html) doc examples :wink:
