### ISSUE TITLE
Is it possible to provide a function to generate the lumos config for dev net?

### ISSUE THREAD

**Issue by Daryl-L** [nervosnetwork/lumos#510]
**Is your feature request related to a problem? Please describe.**

When I develop in dev net which I run the ckb node myself, I found that I need to find the script outpoint of `Secp256k1Blake160`, `Secp256k1Blake160Multisig` and `DAO` myself to setup the lumos config.

**Describe the solution you'd like**

Maybe lumos could provider a function for developers like me to generate the config, such like `getSecp256k1Blake160Config()`.

**Describe alternatives you've considered**

**Additional context**

**Comment by homura** [comment]
Sound like a common feature, how about adding a function in `@ckb-lumos/config-manager` like this?

```ts
declare function getGenesisScriptConfigs(genesisBlock: Block): {
  SECP256K1_BLAKE160: ScriptConfig;
  SECP256K1_BLAKE160_MULTISIG: ScriptConfig;
  DAO: ScriptConfig;
}
```

Usage:

```ts
getGenesisScriptConfigs(await rpc.getBlockByNumber('0x0'));
```

**Comment by Daryl-L** [comment]
> Sound like a common feature, how about adding a function in `@ckb-lumos/config-manager` like this?
> 
> ```ts
> declare function getGenesisScriptConfigs(genesisBlock: Block): {
>   SECP256K1_BLAKE160: ScriptConfig;
>   SECP256K1_BLAKE160_MULTISIG: ScriptConfig;
>   DAO: ScriptConfig;
> }
> ```
> 
> Usage:
> 
> ```ts
> getGenesisScriptConfigs(await rpc.getBlockByNumber('0x0'));
> ```

I think it is great
