### ISSUE TITLE
[Question] How to import the next Lumos version?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#513]
As per title, I'm wondering: within a Lumos typescript, what's the most idiomatic way to add as dependency the next Lumos version?

Right now I'm doing:
```json
  "dependencies": {
    "ckb-lumos": "https://github.com/ckb-js/lumos#74e1c05"
  },
```

But in the end it complains:
```bash
user@host:~/v1-bot-demo$ npm run build

> v1-bot-demo@1.0.0 build
> tsc

node_modules/ckb-lumos/packages/e2e-test/src/utils.ts:1:24 - error TS2307: Cannot find module '@ckb-lumos/base' or its corresponding type declarations.

1 import { Script } from "@ckb-lumos/base";
                         ~~~~~~~~~~~~~~~~~

node_modules/ckb-lumos/packages/e2e-test/src/utils.ts:2:33 - error TS2307: Cannot find module '@ckb-lumos/helpers' or its corresponding type declarations.

...
```

I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
Hi, you can import the next Lumos version by doing this

1. Check the next version of the Lumos

```sh
npm view @ckb-lumos/base
```

```
dist-tags:
latest: 0.19.0        next: 0.20.0-alpha.2
```

2. Append the Lumos in your `dependencies` of the `package.json`

```json
{
  "dependencies": {
    "@ckb-lumos/base": "^@0.20.0-alpha.2"
  }
}

```

**Comment by phroi** [comment]
Thank you @homura, that was informative, every day you teach me something new! :pray:

In my case I wanted to import [e2e-test randomSecp256k1Account](https://github.com/ckb-js/lumos/blob/develop/packages/e2e-test/src/utils.ts) that right now is not exported as a module. For now I chose to directly copy-paste the full raw `utils.ts` file and when the module will be exported I'll just import that.
