### ISSUE TITLE
[Question] How to create a dep group transaction in Lumos?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#515]
As per title, I'm wondering: within a Lumos typescript, what's the most idiomatic way to build a transaction that create a dependency group?

So as far as I understand it's just a normal cell within a normal transaction with the data serialized in a specific way.

The only practical reference I found is from the [RFC Transaction Structure](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0022-transaction-structure/0022-transaction-structure.md#dep-group):
> Dep Group stores the serialized list of `OutPoint` in cell data. Each `OutPoint` points to one of the group members.

The only implementation reference on how to `serialize` this data is from the [nervosnetwork/ckb](https://github.com/nervosnetwork/ckb/blob/93fe7503d561a5b642bfd0893dc0a4c6fe7df7d6/spec/src/lib.rs#L833):
```rust
let (outputs, outputs_data): (Vec<_>, Vec<_>) = self
.genesis
.dep_groups
.iter()
.map(|dep_group| {
    let out_points: Vec<_> = dep_group
        .files
        .iter()
        .map(|res| {
            let data: Bytes = res.get()?.into_owned().into();
            let data_hash = packed::CellOutput::calc_data_hash(&data);
            let out_point = find_out_point_by_data_hash(cellbase_tx, &data_hash)
                .ok_or_else(|| {
                    format!("Can not find {res} in genesis cellbase transaction")
                })?;
            Ok(out_point)
        })
        .collect::<Result<_, Box<dyn Error>>>()?;

    let data = out_points.pack().as_bytes();
    let cell = packed::CellOutput::new_builder()
        .lock(self.genesis.system_cells_lock.clone().into())
        .build_exact_capacity(Capacity::bytes(data.len())?)?;
    Ok((cell, data.pack()))
})
.collect::<Result<Vec<(packed::CellOutput, packed::Bytes)>, Box<dyn Error>>>()?
.into_iter()
.unzip();
```

@homura now I'm wondering: how to actually serialize that data within a Lumos typescript?

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
The most serialization format is used in CKB is [molecule](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0008-serialization/0008-serialization.md), which is implemented in [`@ckb-lumos/codec`](https://github.com/ckb-js/lumos/tree/develop/packages/codec). Here is an example to show how to `(un)pack` an `OutPointVec`

```ts
import { molecule } from "@ckb-lumos/codec";
// the blockchain.mol from https://github.com/nervosnetwork/ckb/blob/5a7efe7a0b720de79ff3761dc6e8424b8d5b22ea/util/types/schemas/blockchain.mol
import { blockchain } from "@ckb-lumos/base";

const { vector } = molecule;
const { OutPoint } = blockchain;

const OutPointVec = vector(OutPoint);
// the transaction[1].outputs[0] from the genesis block
// https://explorer.nervos.org/transaction/0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c#1
const deserialized = OutPointVec.unpack(
  "0x02000000e2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c03000000e2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c01000000"
);
const serialized = OutPointVec.pack(deserialized);

console.log(deserialized);
console.log(serialized);

```

And we can check out more [examples](https://github.com/ckb-js/lumos/tree/develop/packages/codec) to learn how to use the module.

And Lumos also provided a deserializing tool [online](https://lumos-website.vercel.app/tools/molecule-parser).
<img width="786" alt="image" src="https://github.com/ckb-js/lumos/assets/7511174/511843d8-c5d6-499a-aa59-240a9c9995d0">

**Comment by phroi** [comment]
What a complete answer!! @homura thanks to you every day I learn a bit more about Nervos L1, thanks a lot! :pray:
