### ISSUE TITLE
[Suggestion] Switch `BI` implementation to `BigInt`

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#519]
The behaviour of `BI` `<` operator is misleading:

```
import { BI } from "@ckb-lumos/bi"
const a = BI.from(2);
const b = BI.from(10);
console.log("a < b : ", a < b);
console.log("a.lt(b) : ", a.lt(b));
```
Returns:
> a < b :  false
> a.lt(b) :  true

Keep up the great work :muscle:
Phroi

**Comment by phroi** [comment]
@homura I was thinking, Lumos is gonna natively support BigInt, what if the BI implementation switched to BigInt?

**Why?** This would prevent bugs like this one and enable slimmer syntax when using it. 👆 Also it could open the path for phasing BI out if needed.

**How?** I did a little bit of digging and [it's not straightforward to subclass BigInt](https://github.com/tc39/proposal-bigint/issues/98), but we could [directly define the old but useful BI methods on BigInt](https://stackoverflow.com/questions/58265985/extending-built-in-types-in-typescript) and aliasing BigInt as BI :thinking:

**Comment by homura** [comment]
It may not be a good practice to directly define the BI methods in `BigInt`. 

- security: modifying a native object can cause security issues and lead to unexpected results. A proposal called [SES](https://github.com/tc39/proposal-ses) was introduced to avoid modifying native objects
- conflict: defining BI methods in `BigInt` can result in namespace pollution. If multiple libraries are trying to define BI methods in `BigInt`, it can lead to conflicts and unpredictable behavior
- breaking change: switching an `object` to a `primitive` can be a breaking change. The behaviors such as `===` or `==`, and `instanceof`, are different from the current version

**Comment by phroi** [comment]
Yeah, makes sense, thanks @homura for taking your time for explaining this to me! :pray:
