### ISSUE TITLE
[Question] What's the role of fixedEntries in a TransactionSkeleton?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#522]
As per title, I'm wondering: within a Lumos typescript, what's the role of `fixedEntries` in a TransactionSkeleton?

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
`fixedEntries` in a `TransactionSkeleton` defines a list of entries that are considered "fixed" and should not be changed while generating or modifying the transaction. 

This is useful when working with specific cells in a transaction that you don't want to be modified by other functions in `@ckb-lumos/common-scripts` and operations while building the transaction.

![image](https://github.com/ckb-js/lumos/assets/7511174/2a037fa6-a698-4124-b968-496a00fccb3a)

**Comment by phroi** [comment]
Good to know!! Thank you @homura, for the complete response and the drawing, very appreciated! :pray:
