### ISSUE TITLE
[Question] What's the best way to choose a mining fee?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#523]
As per title, I'm wondering: within a Lumos typescript, what's the best way to choose a mining fee?

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
AFAIK, there may not be the best way to pick a `fee_rate`, but I know these methods to help us to pick a `fee_rate`

- `tx_pool_info`: to pick the lowest cost
- `get_fee_rate_statistics`: to pick the latest 1 - 101 blocks mean and median `fee_rate`

To determine the `weight` of a transaction, we should 

1. [`estimate_cycles`](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md#method-estimate_cycles) * [`DEFAULT_BYTES_PER_CYCLES`](https://github.com/nervosnetwork/ckb/blob/20054f010e32ecaa5587534f4adb0b2410b453ae/util/types/src/core/tx_pool.rs#L250) 
2. `getTransactionSizeByTx`
3. pick the larger one as the `weight`

In Lumos, we can use the

- `common.payFee` to pay by specific values
- `common.payFeeByFeeRate` to pay by a `fee_rate`
