### ISSUE TITLE
Optimize the release workflow

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#530]
## Motivation

Some Lumos users got sucks when they were trying to upgrade the `lumos@0.18` to `lumos@0.19`, since the breaking tip in the changelog is not obvious enough

So we should optimize the release workflow

- make the changelog more clearly labeled with breaking changes
- make sure the changelog has been reviewed before releasing Lumos

## How to

- find (or make) a tool to label the change type in the changelog
  - (candidate)[lerna-changelog](https://github.com/lerna/lerna-changelog)
  - (candidate)[lerna](https://github.com/lerna/lerna)
  - (candidate)[changesets](https://github.com/changesets/changesets)
- a new PR specifically for release
  - release by a reviewed PR instead of by push to some certain branch

### A Quick Try

It would be nice to have a quick try by `npm install @ckb-lumos/lumos@canary` when a pull request has merged

**Comment by homura** [comment]
After research and experience, it was found that the `changesets` would be more appropriate. 

1. `changesets` support adding more than one changelog in a pull request by multiple `npx changest add`, this is a great help to a monorepo to organize changelog
2. `changesets` has provided an [`action`](https://github.com/changesets/action) to update changelog for every merged pull request by an [automatic pull request](https://github.com/homura/lumos-experimental/pull/8), this means we can review the changes before releasing
3. The `major`, `minor` and `patch` heading is easy to check whether a breaking change was happened

## Demo

- [pull request with changeset](https://github.com/homura/lumos-experimental/pull/2)
- release (next)
  - [preview changes](https://github.com/homura/lumos-experimental/pull/8)
  - [release](https://github.com/homura/lumos-experimental/actions/runs/5568553821/jobs/10171261332)
- release (latest)
  - [preview changes](https://github.com/homura/lumos-experimental/pull/9) 
  - [release](https://github.com/homura/lumos-experimental/actions/runs/5568645649/jobs/10171434448)

**Comment by homura** [comment]
[Canary](https://github.com/homura/lumos-experimental/actions/runs/5597902966/jobs/10236873348#step:7:32) release has been supported, a `0.0.0-canary-{short hash}-{datetime}` will be released to npm registry when the pull requests are merged to `develop`

**Comment by Keith-CY** [comment]
FYI, a brief workflow to publish of kuai at https://github.com/ckb-js/kuai/issues/360#issuecomment-1631057860

**Comment by homura** [comment]
A collection of reusable actions:  https://github.com/Magickbase/shaping/issues/45#issuecomment-1517546521
