### ISSUE TITLE
[Question] How to write a Lumos codec for a variable sized field?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#539]
As per title, I'm wondering: within a Lumos typescript, what's the best way to write a codec for a variable sized field?

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by phroi** [comment]
Right now I'm attempting something like this:

```
import { bytes } from "@ckb-lumos/codec";
import { byteVecOf } from "@ckb-lumos/codec/lib/molecule/helper";
import { struct } from "@ckb-lumos/codec/lib/molecule/layout";
import { Uint256, Uint256LE, Uint64, Uint8 } from "@ckb-lumos/codec/lib/number";

const UTF8String = byteVecOf<string>({
    pack: (str) => {
        return Uint8Array.from(Buffer.from(str, "utf8"));
    },
    unpack: (buf) => {
        return Buffer.from(bytes.bytify(buf)).toString("utf8");
    },
});

const Script /*: Codec */ = struct(
    {
        codeHash: Uint256,
        hashType: Uint8,
        args: UTF8String,
    },
    ["codeHash", "hashType", "args"]
);


const LimitOrderInfo /*: Codec */ = struct(
    {
        sudtHash: Uint256,
        isSudtToCkb: Uint8,
        sudtMultiplier: Uint64,
        ckbMultiplier: Uint64,
        script: Script,
    },
    ["sudtHash", "isSudtToCkb", "sudtMultiplier", "ckbMultiplier", "script"]
);
```

But errors out with:
> Type 'BytesCodec<string, string>' is not assignable to type 'FixedBytesCodec'.
  Type 'Codec<Uint8Array, string, string, BytesLike>' is missing the following properties from type 'Fixed': __isFixedCodec__, byteLength
  
So I'm wondering, how should I write a Codec containing a variable size field?

**Comment by homura** [comment]
https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0008-serialization/0008-serialization.md

A fixed-size layout **CANNOT** contain a dynamic-size type. The `struct` cannot contain a `vector` because `struct` is fixed-size while `vector` is dynamic. 

I am guessing the example below might be what you need

```ts
const MyScript = table(
  {
        codeHash: Uint256,
        hashType: Uint8,
        args: UTF8String,
  }, 
['codeHash', 'hashType', 'args']
)
```

**Comment by phroi** [comment]
Thanks for the reference, good to see this on a RFC! :muscle:

I would have used a `table`, but it adds way too much overhead in occupied capacity.

In the end for encoding Limit Order Script Args I settled on an approach using `struct`, but parametric to the number of bytes of `Args`. In this way different `Args` lengths correspond to different `struct` codecs. Also this is the encoding currently used by Limit Order Script Args contract.

```
const createParametricLimitOrderCodec = (argsLength: number) => {
    const ParametricScriptCodec = struct(
        {
            codeHash: Byte32,
            hashType: HashTypeCodec,
            args: createFixedHexBytesCodec(argsLength),
        },
        ["codeHash", "hashType", "args"]
    );

    return struct(
        {
            sudtHash: Byte32,
            isSudtToCkb: Uint8,
            sudtMultiplier: Uint64,
            ckbMultiplier: Uint64,
            terminalLock: ParametricScriptCodec,
        },
        ["sudtHash", "isSudtToCkb", "sudtMultiplier", "ckbMultiplier", "terminalLock"]
    );
}

interface LimitOrderFields {
    sudtHash: BytesLike,
    isSudtToCkb: BIish,
    sudtMultiplier: BIish,
    ckbMultiplier: BIish,
    terminalLock: {
        codeHash: BytesLike,
        hashType: HashType,
        args: HexString
    }
}

const minLimitOrderLength = createParametricLimitOrderCodec(0).byteLength;

export const LimitOrderCodec = {
    pack: (fields: LimitOrderFields) =>
        createParametricLimitOrderCodec((fields.terminalLock.args.length - 2) / 2).pack(fields),
    unpack: (data: Uint8Array) =>
        createParametricLimitOrderCodec(data.length - minLimitOrderLength).unpack(data),
};
```

Example of use:
```
const packedData = LimitOrderCodec.pack(
    {
        sudtHash: Array.from({ length: 32 }, () => 0),
        isSudtToCkb: 0,
        sudtMultiplier: 0,
        ckbMultiplier: 0,
        terminalLock: {
            codeHash: Array.from({ length: 32 }, () => 0),
            hashType: "data",
            args: "0x",
        }
    }
);

console.log("Packed length:", packedData.length);
console.log(LimitOrderCodec.unpack(packedData));
```

Prints:

> Packed length: 82
> {
>   sudtHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
>   isSudtToCkb: 0,
>   sudtMultiplier: BI { jsbi: JSBI(0) [ sign: false ], _isBI: true },
>   ckbMultiplier: BI { jsbi: JSBI(0) [ sign: false ], _isBI: true },
>   terminalLock: {
>     codeHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
>     hashType: 'data',
>     args: '0x'
>   }
> }


@homura do you see any issues with this approach?

**Comment by homura** [comment]
I guess the `ParametricLimitOrder` is not a regular molecule shape, right? The size of the last field `args` is dynamic. If it is, I'd suggest to splitting the `ParametricLimitOrderCodec` into two parts

First, let's separate the fixed-size part

```ts
// the `args` was separated from the struct
const OrderConfigCodec = struct(
  {
    sudtHash: Byte32,
    isSudtToCkb: Uint8,
    sudtMultiplier: Uint64,
    ckbMultiplier: Uint64,
    codeHash: Byte32,
    hashType: HashTypeCodec,
  },
  ["sudtHash", "isSudtToCkb", "sudtMultiplier", "ckbMultiplier", "codeHash", "hashType"]
);
```

Second, let's create a custom `OrderArgsCodec`

```ts
const OrderArgsCodec = createBytesCodec<{ args: string }, { args: BytesLike }>({
  pack: (unpacked) => bytes.bytify(unpacked.args),
  unpack: (packed) => ({ args: bytes.hexify(packed) }),
});
```

Finally, compose them together

```ts
type PackableOrder = PackParam<typeof OrderConfigCodec> & PackParam<typeof OrderArgCodec>;
type UnpackedOrder = UnpackResult<typeof OrderConfigCodec> & UnpackResult<typeof OrderArgCodec>;

const OrderParameterCodec = createBytesCodec<UnpackedOrder, PackableOrder>({
  pack: (unpacked) => {
    return bytes.concat(OrderConfigCodec.pack(unpacked), OrderArgCodec.pack(unpacked));
  },
  unpack: (packed): UnpackedOrder => {
    const packedConfig = packed.slice(0, OrderConfigCodec.byteLength)
    const packedArgs = packed.slice(OrderConfigCodec.byteLength)

    const config = OrderConfigCodec.unpack(packedConfig);
    const args = OrderArgsCodec.unpack(packedArgs);

    return { ...config, ...args };
  },
});
```

**Comment by phroi** [comment]
Among the solutions that came to mind yesterday, I tried this one, but without knowing all the templating involved and only basic knowledge about Molecule serialization I was not able to write a `OrderArgsCodec` like the one you proposed.

Both solutions serialize in the same way, still I recognize that the one you proposed is conceptually cleaner, so [I switched to your solution](https://github.com/ickb/v1-bot-demo/commit/90bf12bc949ef9e0d41596fdc69f6ed8576229dd), thanks again :pray:
