### ISSUE TITLE
[Question] How to simulate the validity of a transaction?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#547]
As per title, I'm wondering: within a Lumos typescript I build a transaction, but I'm not sure if it's valid or not, what's the best way to simulate its validity?

Expected results:
In case it's **invalid**, I just want to know that it doesn't validate and the **error code**.
In case it's **valid**, I just want to know that it validate, but I **don't** want to **commit** the result to L1.

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
## Devnet

- [Run a CKB Dev Blockchain](https://docs.nervos.org/docs/basics/guides/devchain/)
- [Deploy Contracts Via Lumos](https://lumos-website.vercel.app/api/modules/_ckb_lumos_common_scripts.html#md:usage)

## CKB Standalone Debugger

[CKB standalone debugger](https://github.com/nervosnetwork/ckb-standalone-debugger) is a `ckb-script` & `ckb-vm` wrapper that enabling debug the transaction off-chain

- [CKB Transaction Dumpper](https://github.com/nervosnetwork/ckb-transaction-dumper)


```sh
# the transaction in my-tx.json should 
# be consistent with the structure of the RPC
ckb-transaction-dumper --tx my-tx.json --output dump.json
```

- [CKB Debugger](https://github.com/nervosnetwork/ckb-standalone-debugger/tree/develop/ckb-debugger)

```sh
ckb-debugger --dump-file dump.json \
  --cell-index 0 \ # indicates the index of cells to run
  --cell-type input # indicates input/output cell to run
```

## Lumos Debugger Wrapper

`@ckb-lumos/debugger` is a wrapper of the `ckb-debugger` for internal use, so it is unreleased yet.

- [Clone the lumos repo and treat it as a submodule](https://github.com/ckb-js/lumos/issues/525#issuecomment-1594519557)
- The [test case](https://github.com/ckb-js/lumos/blob/develop/packages/debugger/tests/context.test.ts#L106-L142) demonstrated how to use the debugger

**Comment by phroi** [comment]
I asked a [very similar question on Nervos Talk](https://talk.nervos.org/t/how-to-fork-mainnet-l1-into-a-devnet/7329/), but I was not really sure how `ckb-deugger` worked until I read your reply, thanks @homura!! :pray:

Lumos Debugger Wrapper, interesting, good to know for next time! :muscle:

Wish you a nice day,
Phroi
