### ISSUE TITLE
Predefined LockScriptInfos cannot be replaced

### ISSUE THREAD

**Issue by ShookLyngs** [nervosnetwork/lumos#548]
**Describe the bug**

Not sure if this is a feature, please help me identify it.

Firstly, let's check the code:

https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/common.ts#L80-L87

You can see the predefined LockScriptInfos and the custom LockScriptInfos are just two list added up together, without filters or anything. So what should I do if I don't want to use some of the predefined logic in `predefinedInfos`?

For instance, if I want to write my own `secp256k1Blake160` LockScriptInfo, how can I cover/replace the predefined one?

**Comment by homura** [comment]
May I ask why you need to override the predefined script here? Almost all methods in the common provide a `config` as a parameter, such as [transfer](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/common.ts#L197), [payFee](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/common.ts#L438).

In my opinion, I don't recommend resorting to a stateful Lumos to manage scripts config for a dApp because Lumos' `ScriptConfigs` is a global variable and it may conflict in some unexpected situations, but if you have to, you can change the default configuration by 

```ts
import { config } from '@ckb-lumos/lumos'

config.initializeConfig({
  PREFIX: 'ckb', // or 'ckb'
  SCRIPTS: {
    SECP256K1_BLAKE160: {
      ...
    }
  }
})

```

**Comment by ShookLyngs** [comment]
Lumos has provide some predefined LockScriptInfo: secp, multisig, acp and omnilock.
In my case, I wanted to overwrite the acp info so I could test the acp functionality with my own methods, without affecting other types of locks and their infos.

**Comment by homura** [comment]
> In my case, I wanted to overwrite the acp info so I could test the acp functionality with my own methods, without affecting other types of locks and their infos.

If the override of the default config is necessary, the `config.initializeConfig` [can be a solution](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/examples/pw-lock-metamask/lib.ts#L6-L21), by replacing the `ANYONE_CAN_PAY` with your custom one

**Comment by ShookLyngs** [comment]
> If the override of the default config is necessary, the `config.initializeConfig` [can be a solution](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/examples/pw-lock-metamask/lib.ts#L6-L21), by replacing the `ANYONE_CAN_PAY` with your custom one

The solution only replaces the default codeHash/cellDeps, etc. But I was trying to replace the common methods for each lock info, such as the "prepareSigningEntries" method of acp. On second thought, maybe I can write my own "common.prepareSigningEntries" and generate a custom lock info list by myself.

**Comment by homura** [comment]
> But I was trying to replace the common methods for each lock info, such as the "prepareSigningEntries" method of acp

I am not sure whether I've missed some context of the question, the [`acp.prepareSigningEntries`](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/anyone_can_pay.ts#L445) is using the `config` from `initializeConfig`, so as I understand, the `initializeConfig` is enough to reach your requirement

**Comment by ShookLyngs** [comment]
> I am not sure whether I've missed some context of the question, the [`acp.prepareSigningEntries`](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/anyone_can_pay.ts#L445) is using the `config` from `initializeConfig`, so as I understand, the `initializeConfig` is enough to reach your requirement

The `initializeConfig` method is for changing the global default config of lumos, but in my case the config has nothing need to be changed. I was trying override the `acp.prepareSigningEntires` method so it handle things differently than the original method, but the acp's script info is the same as in the predefined config.

**Comment by ShookLyngs** [comment]
> I am not sure whether I've missed some context of the question, the [`acp.prepareSigningEntries`](https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/anyone_can_pay.ts#L445) is using the `config` from `initializeConfig`, so as I understand, the `initializeConfig` is enough to reach your requirement

The `initializeConfig` method is for changing the global default config of lumos, but in my case there's nothing need to be changed about the config itself. I wanted to override the `acp.prepareSigningEntires` method so it handle things differently than the original method, but the acp's script info is the same as in the predefined config.

**Comment by ShookLyngs** [comment]
As an actual example, I wanted to change this part of the `acp.prepareSigningEntries`:

https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/anyone_can_pay.ts#L481-L484

Change the unpack part to:
```typescript
.map((output) => number.Uint128LE.unpack(output.data.slice(2, 34))) 
```

**Comment by homura** [comment]
> As an actual example, I wanted to change this part of the `acp.prepareSigningEntries`:
> 
> https://github.com/ckb-js/lumos/blob/6bb442cb864484efa40020860a254cac219427e2/packages/common-scripts/src/anyone_can_pay.ts#L481-L484
> 
> Change the unpack part to:
> 
> ```ts
> .map((output) => number.Uint128LE.unpack(output.data.slice(2, 34))) 
> ```

Does it mean you are using another lock script with ACP-like logic? But the lock is actually not the ACP lock, right?

**Comment by ShookLyngs** [comment]
> Does it mean you are using another lock script with ACP-like logic? But the lock is actually not the ACP lock, right?

I am using the official ACP lock, but curerntly lumos' `acp.prepareSigningEntries` doesn't unpack the first 16 bytes of the `cell.data`, it just unpacks the whole `cell.data`. So if a SUDT cell has provided more info in the `cell.data`, the method will throw an error and say the `cell.data`'s length is incorrect.

To test if the `acp.prepareSigningEntries` works if it only unpacks the first 16 bytes of each cell's data, I copied and changed the internal logic of the `acp.prepareSigningEntries` method, the last step was to find a way and override the predefined LockScriptInfos, or I can to write a new `prepareSigningEntries` method instead of using the `common.prepareSigningEntries` method.

Or do you have time to fix the `unpacking the first 16 bytes` issue first? 
In that case I can use the latest version of lumos to avoid it, instead of dirty fixing it.

**Comment by homura** [comment]
> Or do you have time to fix the `unpacking the first 16 bytes` issue first?
> In that case I can use the latest version of lumos to avoid it, instead of dirty fixing it.

I've created one https://github.com/ckb-js/lumos/pull/549

**Comment by ShookLyngs** [comment]
> I've created one #549

Thanks a lot! hoping to see it soon!

**Comment by homura** [comment]
@ShookLyngs Hi, a [canary](https://github.com/ckb-js/lumos/commit/5d1862fca2de473ef047cef3044f0cb5a2d9b2d7#commitcomment-123776149) is released, maybe you can have a try

**Comment by ShookLyngs** [comment]
> @ShookLyngs Hi, a [canary](https://github.com/ckb-js/lumos/commit/5d1862fca2de473ef047cef3044f0cb5a2d9b2d7#commitcomment-123776149) is released, maybe you can have a try

I've tested the cannary version, the issue is no longer there.
