### ISSUE TITLE
config  not support data2 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/lumos#563]
should add data2 
https://github.com/ckb-js/lumos/blob/1c331530f1b5075fc8d4d7d9b81de13be818edfb/packages/config-manager/src/manager.ts#L45

**Comment by homura** [comment]
https://github.com/ckb-js/lumos/commit/cbab8d9882e52e730dba8c3c362c9ffce9b81b78

Supported, please reinstall lumos@2023 and try it again
