### ISSUE TITLE
Custom indexer powered by animagus

### ISSUE THREAD

**Issue by xxuejie** [nervosnetwork/lumos#57]
Due to schema design, the indexer included in lumos can only provide certain kinds of queries. While this is enough for most dapps, there might always be different dapps that require different indexing solution.

Custom indexer solves this problem, by leveraging the AST model designed in animagus, we can enable developers to index any kind of data in CKB as they wish. This will greatly improve the flexibility of lumos.

**Comment by homura** [comment]
Close the issue due to inactivity
