### ISSUE TITLE
SQL indexer based on Rust

### ISSUE THREAD

**Issue by xxuejie** [nervosnetwork/lumos#58]
Right now we do have a JS based SQL indexer, the problem with this, is that it might not be the best way to extract all the computing power of a machine. We might want to build a different indexer, that is powered by Rust, so we can better leverage native code to speed up block executions, while at the same time, enjoy the benefits in a modern multi-core machine.

**Comment by homura** [comment]
Lumos doesn't the support native indexer anymore, so we can close this issue
