### ISSUE TITLE
Fee calculator based on fee rate

### ISSUE THREAD

**Issue by xxuejie** [nervosnetwork/lumos#62]
Right now, `payFee` method provided by lumos only allows one to enter a fee directly. Ideally, we should be able to calculate fee based on each transaction. Specifically, we can achieve this in the following path:

1. Generate a transaction from the TransactionSkeleton
2. Serialize the transaction to molecule format, and obtain its size
3. Based on a fee rate and the transaction size, we can generate the fee to pay
4. Now invoke `payFee` to add the fee to pay

Notice `payFee` might need to insert yet another input cell, creating a larger transaction than the original, this means we will probably have to compensate for the added part in step 2.

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/lumos/pull/93
