### ISSUE TITLE
How lumos generate immature transaction?

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/lumos#63]
A immature transaction is a transaction its `inputs`/`cell_deps` have immature cells or `header_deps` have immature headers.

As I understand currently design of `lumos` can't generate immature transaction. For case like payment channel, one side may need to generate a transaction depend on an immature header, then send it to other side to partially sign the transaction, it would be inconvenient to do this in `lumos`.

Is there any plan to support this feature?

**Comment by xxuejie** [comment]
This is a very good question, and something we haven't tackled well right now. We should indeed consider this.

**Comment by homura** [comment]
https://github.com/nervosnetwork/rfcs/blob/01f3bc64ef8f54c94c7b0dcf9d30c84b6c8418b0/rfcs/0036-remove-header-deps-immature-rule/0036-remove-header-deps-immature-rule.md

the immature rule has been removed
