### ISSUE TITLE
[Question] How to deploy a L1 Script referenced by Type?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#638]
As per title, I'm wondering: how to deploy with Lumos a L1 script that will be referenced by **Type**?

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
@phroi Hi, we've created an example https://github.com/ckb-js/lumos/pull/639/ to show how to use the `generateDeployWithTypeIdTx` API

**Comment by phroi** [comment]
Now I even remember finding this method a few months ago and being confused on how to use it :sweat:

With your example, it makes much more sense!! Now that I took a look at the [deploy implementation](https://github.com/ckb-js/lumos/blob/develop/packages/common-scripts/src/deploy.ts), I notice that you may want to export the interfaces, otherwise [in the docs](
https://lumos-website-git-develop-magickbase.vercel.app/api/variables/_ckb_lumos_common_scripts.deploy.html) `options` type is not clickable and not documented in any way.

Thanks again @homura for taking your time to reply!! :pray:

**Comment by homura** [comment]
Hi, @phroi, I noticed that the `Fixes #x` mark in the PR description closed this issue automatically, please feel free to reopen this issue when you have any question about deploying scripts with TypeID.
