### ISSUE TITLE
[Question] How to generate private key in Web Worker?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#664]
As per title, I'm wondering: How to safely generate a `secp256k1_blake160` private key within a Browser Web Worker?

I read [lumos HD tutorial](https://lumos-website.vercel.app/#2-generate-a-wallet-account), but the underlying [`generateMnemonic`](https://github.com/ckb-js/lumos/blob/4f2e4535cb788c90f9facb4dd54a30ba3bff8dc2/packages/hd/src/mnemonic/index.ts#L173) is not browser compatible as it depends on NodeJS's crypto library, so in this case it's not a good solution.

After exploring a bit I understood that using Web Crypto API's [SubtleCrypto.generateKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey) seems to be the correct choice and it can be accessed within a Web Worker by using the syntax `self.crypto.subtle.generateKey`, just I'm confused about which [parameters](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey#parameters) to use for generating a `secp256k1_blake160` private key 🤔

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
To use the `generateMnemonic` function in a browser, it is typically necessary to use the [`crypto-browserify`](https://github.com/browserify/crypto-browserify) polyfill to create a random seed for generating the mnemonic. This function relies on the `getRandomValues` method provided by the [`window.crypto`](https://github.com/browserify/randombytes/blob/b4eb4126fccc503e375853ca7b3e96aaa34af9e6/browser.js#L16) module to generate a secure random number, which is crucial for generating a valid mnemonic. 

However, I strongly advise against generating any sensitive data on a page without a sandbox mechanism, as there are numerous potential risks that could result in the disclosure of sensitive data. For example, a simple monkey patch

<img width="355" alt="image" src="https://github.com/ckb-js/lumos/assets/7511174/36f8115c-d082-48d4-98fb-0a5d0c3e1120">

```js
const U8A = globalThis.Uint8Array
globalThis.Uint8Array = class extends U8A {
    constructor(...args) {
        super(...args)
        console.log('your key is mine now', args)
    }
}

new Uint8Array([1,2,3,4,5])
```

**Comment by phroi** [comment]
Hey @homura, I appreciate your concern!! :hugs: 

I'd like to point out two details:
- I was asking about `generateKey` parameters as [`getRandomValues` is advised against for key generation](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues#usage_notes):
> Prefer the [generateKey()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey) method for key generation, which is guaranteed to be running in a secure context.
- Web Worker itself is indeed kind of a sandbox, [within a webpage it's the safest place to run these computations](https://auth0.com/blog/secure-browser-storage-the-facts/#Web-Workers-Help-Maintain-Secure-Browser-Storage). If the attack you propose happens within the webpage code (say a malicious UI library), then it does not have any effect on the Web Worker Environment. 

The private key lifecycle in my use case would be the following:
1. At the beginning the Session Key is generated as safely as possible within the WebWorker
2. Session Key never leaves the WebWorker (not for backup not for storing to disk)
3. User deploy a cell where he hardcodes the public key into a script (this script is a Type ID so it's updatable in the next session)
4. Session Key is used within the WebWorker to sign a finite set of transactions (the transaction is prepared in the webpage, sent as message to the WebWorker, validated and if not malicious signed).
5. At the end, Session Key is forgotten.

Since you have more experience than me in this topic, let me ask a few more questions:
- Does any other kind of attack come to mind?
- Which other kind of sandbox would you suggest?
- I could switch this code to Rust (compiled to WASM) in a Web Worker, does any drawback come to mind?

**Comment by homura** [comment]
> I was asking about `generateKey` parameters as [getRandomValues is advised against for key generation](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues#usage_notes):

I mistakenly assumed that you'd use `generateMnemonic` to generate BIP39 secp256k1 private keys. As a result, I included information related to `getRandomValues`, which is used to generate mnemonics

> Web Worker itself is indeed kind of a sandbox, [within a webpage it's the safest place to run these computations](https://auth0.com/blog/secure-browser-storage-the-facts/#Web-Workers-Help-Maintain-Secure-Browser-Storage). If the attack you propose happens within the webpage code (say a malicious UI library), then it does not have any effect on the Web Worker Environment.

I understand that you're planning to generate some one-time private keys to send temporary transactions. According to the blog you shared, you can use Web Worker as a sandbox for an independent environment to generate and sign the message. However, as I'm not an expert on Web Worker, I cannot confirm if it's secure enough to carry out your task.

Moreover, consider using curves besides secp256k1, such as secp256r1(used in JoyID), or ed25519 (used in Omnilock Solana auth id). These curves are [natively supported](https://github.com/WICG/webcrypto-secure-curves/blob/main/explainer.md) by [`crypto.subtle.sign`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign)

**Comment by phroi** [comment]
> Moreover, consider using curves besides secp256k1, such as secp256r1(used in JoyID), or ed25519 (used in Omnilock Solana auth id). These curves are [natively supported](https://github.com/WICG/webcrypto-secure-curves/blob/main/explainer.md) by [`crypto.subtle.sign`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign)

Thanks for the heads-up!! I'm no cryptographer but ED25519 may be indeed a better choice :thinking:

> However, as I'm not an expert on Web Worker, I cannot confirm if it's secure enough to carry out your task.

This is exactly the underlying issue!! We are trying to let users run the iCKB fulfillment bot in the browser. A solution like this offers an acceptable level of automation, requiring only a single user authorization per session. The only question now is: does it have an acceptable level of security?

By any chance, @homura can you advice anybody in the Nervos Ecosystem who could give an expert opinion on this?

**Comment by homura** [comment]
> By any chance, @homura can you advice anybody in the Nervos Ecosystem who could give an expert opinion on this?

I suggest seeking advice from the JoyID developers. Since JoyID is a web-based crypto wallet, they are likely familiar with crypto in browser environments

**Comment by phroi** [comment]
> I suggest seeking advice from the JoyID developers. Since JoyID is a web-based crypto wallet, they are likely familiar with crypto in browser environments

That's a good advice! I guess that I'll create a Nervos Talk post explaining the full idea, from there I can ask advice to JoyID developers. Wish you a nice day, thanks again @homura!! :pray:
