### ISSUE TITLE
[Question] How to use `pnpm` with `Lumos@22`?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#679]
As per title, I'm wondering: what's the correct way to import [`createP2PKHMessageGroup`](https://lumos-website-git-develop-magickbase.vercel.app/api/functions/_ckb_lumos_common_scripts.createP2PKHMessageGroup.html) using `pnpm`?

My previous working solution pre-Lumos@22 & `npm` was:
```
import { createP2PKHMessageGroup } from "@ckb-lumos/common-scripts";
```

With Lumos@22 as per docs I switched the `package.json` dependencies to:
```
  "dependencies": {
    "@ckb-lumos/lumos": "^0.22.2",
  },
```

Now the previous import works nicely with `npm`, but fails with `pnpm`.

Additionally `createP2PKHMessageGroup` does not appear at all in the `node_modules/@ckb-lumos/lumos/common-scripts` dependency created by `pnpm`, but it does appear in `node_modules/.pnpm/@ckb-lumos+common-scripts@0.22.2/node_modules/@ckb-lumos/common-scripts`.

Using `pnpm config set auto-install-peers true` does not solve the problem.

As usual I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by homura** [comment]
To fix the issue, explicitly install `@ckb-lumos/commons-scripts`. Unlike NPM, Pnpm [creates a non-flat node_modules directory](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)

```diff
  "dependencies": {
+	"@ckb-lumos/common-scripts": "^0.22.2",
    "@ckb-lumos/lumos": "^0.22.2",
  },
```

You can try it on [stackblitz](https://stackblitz.com/edit/vitejs-vite-vmchfv)

**Comment by phroi** [comment]
Thank you @homura for the fast reply!! Gotcha, so `@ckb-lumos/lumos@22` does not re-export 100% of the code.

Used in conjunction with `npm`, one can get away with just `"@ckb-lumos/lumos": "^0.22.2"` due to the flat `node_modules` directory.

Used in conjunction  with `pnpm`, it's just cleaner to specify the dependencies in the old way in the `package.json`.

Keep up the Great Work :muscle:
Phroi
