### ISSUE TITLE
How to calculate the fee for sending all balances

### ISSUE THREAD

**Issue by qieman** [nervosnetwork/lumos#705]
I use `common.__tests__.getTransactionSize` to calculate the size of the transaction，So the  transaction fee is` (tx_size + 4) * feeRate / 1000`. But if I need to send all the balance，how to calculate the fee and the actual sending amount

**Comment by homura** [comment]
The transaction fee for sending all balances is calculated in the same manner as for other transactions. You can manually deduct the transaction fee from the receiver's cell in the `outputs`

BTW, it may not be necessary to manually calculate the transaction fee when sending all balances. You can utilize the "payFeeByFeeRate" API and set the fee payee as the receiver using the following code:

```js
txSkeleton = payFeeByFeeRate(txSkeleton, [receiverAddr], feeRate)
```

This API automatically deducts the transaction fee from the `outputs` cell.
