### ISSUE TITLE
Got error when transfer ckb using omni_lock address 

### ISSUE THREAD

**Issue by qieman** [nervosnetwork/lumos#717]
**Describe the bug**
Got error when transfer CKB using omni_lock address :
`Unsupported flag: 18, please check if the script.argsis expected`
It only appear at version 0.23.0, I downgrade lumos to resolve it.

**version**
@ckb-lumos/lumos : 0.23.0

**To Reproduce**
```
 const txSkeleton = await commons.common.transfer(
            _txSkeleton,
            [<omni_lock_address>],
            to,
            BigInt(amount),
        )
```

**Expected behavior**
Not throwing error

**Screenshots**
<img width="890" alt="微信图片_20240621133329" src="https://github.com/ckb-js/lumos/assets/9875305/42cf2d32-c3bb-43e1-b9eb-4c5d86caf79d">

**Comment by homura** [comment]
This error indicates that Lumos does not currently support the auth flag 18. We will add support ASAP

**Comment by homura** [comment]
Hi @qieman , the auth flag 18 is supported in #718 and has been released as a canary. You can try it out with the following code

```sh
npm install @ckb-lumos/lumos@0.0.0-canary-d279b87-20240624101315
```

Feel free to reopen it if you encounter any issues.
