### ISSUE TITLE
How to parse testnet address to script

### ISSUE THREAD

**Issue by qieman** [nervosnetwork/lumos#727]
**Describe the bug**
I using `helpers.parseAddress` to parse the testnet address : 
"ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgjwcjfz4ta3vgm69vurd2wj6wms52tkmtpqqyffqmh"
to script, but lumos throw error: ` Invalid checksum for ckt1qr.....`

**To Reproduce**
```
helpers.parseAddress('ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgjwcjfz4ta3vgm69vurd2wj6wms52tkmtpqqyffqmh')
```

**Expected behavior**
Not throw error

**Comment by twhy** [comment]
@qieman 
```ts
import { helpers, config } from "@ckb-lumos/lumos";

console.log(helpers.parseAddress(
  'ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgjwcjfz4ta3vgm69vurd2wj6wms52tkmtpqqyffqmh',
  { config: config.TESTNET }
));
```

**Comment by qieman** [comment]
@twhy Thanks for your reply, the problem is solved

**Comment by qieman** [comment]
Emm, I found similar problem when I use `common.transfer` to send ckb.
```
const scriptConfig = network === 'testnet' ? lumosConfig.TESTNET : lumosConfig.MAINNET
let txSkeleton = await commons.common.transfer(
            _txSkeleton,
            (await signer.getAddresses()),
            to,
            BigInt(amount),
            undefined,
            undefined,
            {config: scriptConfig} // pass testnet config
        )
```
Tring to pass testnet config, but it didn't work

**Comment by homura** [comment]
FYI, many network-related functions have a parameter called `options` located at the end. This parameter accepts a `{ config: MAINNET | TESTNET }` to use different network configs. For more detailed information, you can check https://lumos-website.vercel.app/configuration#priority
