### ISSUE TITLE
Create Type id cells

### ISSUE THREAD

**Issue by SpectreMercury** [nervosnetwork/lumos#728]
# Requirement: Support Creating Cells Based on Type ID

## Background: 

talks：https://talk.nervos.org/t/en-cn-misc-single-use-seals/8279/2

In the Type ID method on CKB, every seal on a seal chain must contain the first seal’s ID as genesis information. Type ID ensures that the type script gives cells unique IDs and restricts them from being changed throughout the seal chain’s lifecycle. This ID allows verifiers to retrieve the latest seal easily from a universal indexer on CKB.

## Requirement:

We need the SDK to support the following features:
- Generate Type ID: The SDK should be able to generate a unique Type ID.
- Create Cell with Type ID: The SDK should be able to create a cell with the generated Type ID, ensuring that the Type ID remains immutable throughout the cell’s lifecycle.

**Comment by homura** [comment]
@SpectreMercury We've created an example demonstrating how to create a TypeID cell with Lumos at #731. We hope this example is helpful
