### ISSUE TITLE
Confusing helper function names `generateAddress` and `parseAddress`

### ISSUE THREAD

**Issue by tspoff** [nervosnetwork/lumos#73]
A minor point, but I personally find the function names `generateAddress` and `parseAddress` in [helpers](https://github.com/nervosnetwork/lumos/blob/develop/packages/helpers/src/index.ts#L89) to be confusing. I found myself forgetting what they do and having to look it up a few times.

It isn't intuitive for me that _generating_ an address takes in a Script as input, or that _parsing_ an address results in a Script.

I would consider renaming them something like `scriptToAddress` and `addressToScript` if things are still at an early enough stage to do that.

Curious about others' thoughts.

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/lumos/pull/78

How about this ? Add alias names as `scriptToAddress` and `addressToScript`.

**Comment by tspoff** [comment]
Nice solution - best of both worlds.
Thanks, I'll go ahead and close the issue.
