### ISSUE TITLE
Typo in Indexer lib leads to failure when attempting to collect cells 

### ISSUE THREAD

**Issue by tspoff** [nervosnetwork/lumos#75]
typeOoutPoints -> typeOutPoints

Changing the name seems to fix the error. However, I am still not seeing any cells returned when getting by type script only, but that could still be an issue on my end.

https://github.com/nervosnetwork/lumos/blob/81de436ab48f895e8a139200d6565c02d1bbfca5/packages/indexer/lib/index.js#L185

![image](https://user-images.githubusercontent.com/5606917/89134653-3c76a400-d4ec-11ea-9318-3ee407079bca.png)

**Comment by bitrocks** [comment]
Thanks for your feedback.

> However, I am still not seeing any cells returned when getting by type script only, ...

There's a bug when querying by both `lock` and `type` script, which will be fixed in #76. 

But if you query by `lock` or `type` script only, it would be no problem. Have you checked whether the related cells are already consumed ?

**Comment by bitrocks** [comment]
I gonna close this issue.  Further comments are still welcomed.
