### ISSUE TITLE
Support connecting node via https

### ISSUE THREAD

**Issue by katat** [nervosnetwork/lumos#77]
When trying to connect the lumos indexer to the node `https://lina.ckb.dev`, but it throws the following error:
<img width="843" alt="Screen Shot 2020-08-04 at 1 34 41 PM" src="https://user-images.githubusercontent.com/1587352/89256951-d0b14a00-d657-11ea-9bca-b5d161751f64.png">

I guess it is because lumos indexer currently doesn't support nodes exposed via HTTPs protocol.

**Comment by xxuejie** [comment]
I feel like this is an issue for [ckb-indexer](https://github.com/quake/ckb-indexer)

**Comment by quake** [comment]
I will add tls support in ckb-indexer, however, lumos is using a http client directly without tls support:
https://github.com/nervosnetwork/lumos/blob/6ea89f2009ad2a5fd3932387850a5a37bcdc3551/packages/indexer/native/src/lib.rs#L344

it should be patched in lumos own code

**Comment by quake** [comment]
> I feel like this is an issue for [ckb-indexer](https://github.com/quake/ckb-indexer)

fyi, resolved in https://github.com/quake/ckb-indexer/commit/e4f055d618d9b1bc36a45548ae88d86bdf0c2c19

**Comment by bitrocks** [comment]
Yes, it can be solved by adding tls support in lumos directly. I'll make a patch for it.

**Comment by xxuejie** [comment]
> I will add tls support in ckb-indexer, however, lumos is using a http client directly without tls support:
> https://github.com/nervosnetwork/lumos/blob/6ea89f2009ad2a5fd3932387850a5a37bcdc3551/packages/indexer/native/src/lib.rs#L344
> 
> it should be patched in lumos own code

@quake My mistake, you are indeed correct this is lumos code. Sorry for the trouble.
