### ISSUE TITLE
Native indexer not compatible with Electron's NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by katat** [nervosnetwork/lumos#8]
With `@ckb-lumos/indexer` imported, the `Electron` throws the following error:

```
[22775:0604/163717.522194:INFO:CONSOLE(140)] "Uncaught Error: The module '/Users/kata/repos/dev/nervos/neuron/node_modules/@ckb-lumos/indexer/native/index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).", source: electron/js2c/asar.js (140)
```

I tried [electron-rebuild](https://github.com/electron/electron-rebuild) to see if it can rebuild the native module `indexer` to the compatible version `NODE_MODULE_VERSION 75` used by our current `Electron` version, but it seems the `electron-rebuild` is not able to recognize the `indexer` module and rebuild it. 

For the other native modules, such as sqlite/leveldb/node-sass etc, `electron-rebuild` can automatically rebuild them when the command `electron-rebuild` is executed. So I guess the `indexer` native module is missing a standard configuration in the `node` world for the `electron-rebuild` to recognize it and rebuild it. 

Do you know any ways around this?

**Comment by katat** [comment]
This might be relevant: https://nodejs.org/api/addons.html#addons_building

Also, it might be useful for you to know that Electron will deprecate the non-context aware modules. https://github.com/electron/electron/issues/18397

**Comment by katat** [comment]
Because the native indexer is a `rust-binding`, which `electron-rebuild` does not support yet, it will need to set up a script for the Electron apps to rebuild this module using the same node version as the current Election version uses.

Here is a workaround tutorial: https://neon-bindings.com/docs/electron-apps

To share this knowledge a bit for the other developers, I created a PR to update the README: https://github.com/nervosnetwork/lumos/pull/9

**Comment by xxuejie** [comment]
My question is: why `NODE_MODULE_VERSION` 75 is used here? Is it due to some Electron requirements or is it just due to local environments? lumos is designed to supported the latest stable and LTS versions of node, that is why we are only building for 72(for Node 12.x), and 83(the latest stable Node 14.x).

I'm not sure if using `electron-rebuild` is the best solution here, personally I feel a better way, is that we can target the node version used in electron, assuming there is a way to track it.

**Comment by katat** [comment]
> My question is: why NODE_MODULE_VERSION 75 is used here? Is it due to some Electron requirements or is it just due to local environments?

It is due to the Electron requirements.

`NODE_MODULE_VERSION 75` is a custom version used by Electron, and it is not available in the official releases of nodejs, please see: https://nodejs.org/en/download/releases/.  

> I'm not sure if using electron-rebuild is the best solution here, personally I feel a better way, is that we can target the node version used in electron, assuming there is a way to track it.

The issue is the `NODE_MODULE_VERSION ` of the native modules have to match with the Electron. I think that is why `electron-rebuild` is needed to rebuild the modules according to the installed electron version, instead of basing on the local nodejs version.

**Comment by xxuejie** [comment]
> NODE_MODULE_VERSION 75 is a custom version used by Electron, and it is not available in the official releases of nodejs, please see: https://nodejs.org/en/download/releases/.

I see now, thanks

> The issue is the NODE_MODULE_VERSION of the native modules have to match with the Electron. I think that is why electron-rebuild is needed to rebuild the modules according to the installed electron version, instead of basing on the local nodejs version.

Here I'm actually talking about a different thing: one goal of lumos, is that you shouldn't need to install Rust on your machine for a rebuild of the native module. So I do want to see if there is a way we can provide pre-built electron binaries. There might be a side effect that `electron-rebuild` won't be needed, but my primary focus is that you don't need Rust to re-compile a lot of things. I will see what we can do here.

**Comment by katat** [comment]
> Here I'm actually talking about a different thing: one goal of lumos, is that you shouldn't need to install Rust on your machine for a rebuild of the native module. So I do want to see if there is a way we can provide pre-built electron binaries. There might be a side effect that electron-rebuild won't be needed, but my primary focus is that you don't need Rust to re-compile a lot of things. I will see what we can do here.

I second this approach. 

If we can provide the pre-built binaries for electron, it will be better than requiring the 3rd parties to build for themselves since it requires a few dependencies as you mentioned.

**Comment by xxuejie** [comment]
https://github.com/nervosnetwork/lumos/pull/10 provides a solution for this issue for now.

**Comment by katat** [comment]
Nice work! 👍 

I have left a comment in the PR.
